### ISSUE TITLE
Upgrade HESK 2.5.5 > HESK 2.5.5 / Mods for HESK 1.7

### ISSUE THREAD

**Issue by bastiaanc** [mkoch227/Mods-for-HESK#104]
Hi, When I try to upgrade a ticket system HESK 2.5.5 to HESK 2.5.5 including Mods for HESK 1.7.
I get a sql error. I just won't install.

So I tried to upgrade to 1.6 and from there to 1.7 and that worked. Unfortenately all tickets are over the place again ;-)

**Comment by mkoch227** [comment]
I just ran a clean install of HESK 2.5.5, followed by a Mods for HESK 1.7 install. I did not get any errors. Can you provide the SQL error you got?

**Comment by bastiaanc** [comment]
It said ... cannot connect to sql

**Comment by mkoch227** [comment]
It sounds like a database connection issue then. What process are you using to update this helpdesk?

**Comment by bastiaanc** [comment]
At first I have chosen the install as from a normal HESK installation. After that I tried every other option. I checked the database settings e few times. But it was correct, since I was also able to install with MFH1.6. After that I had upgraded to 1.7. My ticket system was actually modified very much. Maybe that is the reason?

I have one more ticket system that should be upgraded. Maybe you want to do the install, so you can see?

**Comment by mkoch227** [comment]
If you can send me an email with the following, I'll see what happens when I run the install:
- Any credentials needed to access filesystem
- Any credentials needed to access database
- URL of HESK installation to be updated

**Comment by bastiaanc** [comment]
Please give me some time to prepare :-)

Thanks for helping :-)

Van:  Mike Koch <notifications@github.com>
Beantwoorden - Aan:  mkoch227/Mods-for-HESK
<reply+008cacdf06e5c8edf6b54cf6bdfeb924930b351d9076c38d92cf0000000110c28f799
2a169ce032ed661@reply.github.com>
Datum:  maandag 5 januari 2015 18:44
Aan:  mkoch227/Mods-for-HESK <Mods-for-HESK@noreply.github.com>
CC:  Bas Cuppen <bas@cuppen.de>
Onderwerp:  Re: [Mods-for-HESK] Upgrade HESK 2.5.5 > HESK 2.5.5 / Mods for
HESK 1.7 (#104)


If you can send me an email with the following, I'll see what happens when I
run the install:
* Any credentials needed to access filesystem
* Any credentials needed to access database
* URL of HESK installation to be updated
‹
Reply to this email directly or view it on GitHub
<https://github.com/mkoch227/Mods-for-HESK/issues/104#issuecomment-68745304>
.

**Comment by mkoch227** [comment]
Actually, would you be able to send me a backup of the database that hasn't been updated yet? That way I can play around with the data without ruining any production data.

**Comment by mkoch227** [comment]
Closed due to inactivity. If you still need assistance, reopen this same issue.
