### ISSUE TITLE
Language Issue

### ISSUE THREAD

**Issue by bastiaanc** [mkoch227/Mods-for-HESK#105]
Hi,
I have very lazy customers and they think they do not have enough time :-(
Also it is hard to change their behavior. I tried to let them fill in the ticket system, but they keep sending me emails.
So I end up with making a ticket myself.

What is the problem?
My customers speak different languages. They speak Dutch, German and English.
Now if an email is imported, HESK does not know which language the customers speaks.
As soon as I start to reply it results in the wrong language for the customer. For example the English templates are being sent to a German.

Now... would there be a possibility that I could fill in the email address of a known (lazy) customer and specify a language for that email address?

Similar to "Email Bans" but in this case I would tell HESK what language the customer speaks.

I hope that this is not difficult ;-)

Thanks for all you do :-)

**Comment by mkoch227** [comment]
This should be really straightforward to add to 2.0.0: allow staff to choose the preferred language of the customer (also allow it to be changed after ticket creation), and to have the email tool use the customer's language when preparing emails.
