### ISSUE TITLE
Support HTML-formatted Email Templates

### ISSUE THREAD

**Issue by bastiaanc** [mkoch227/Mods-for-HESK#106]
The email templates from HESK are made in plain text.
That is ok, but I learned that a lot of customers did not even read all the small text. They thought there was nothing that was ment for them, although is is very clear and obvious.

Would it be possible to change the email templates in html?
Similar to the attachment?
![schermafbeelding 2015-01-05 om 15 43 54](https://cloud.githubusercontent.com/assets/9219295/5614483/0ab995b6-94f2-11e4-9b26-6e3da68fb524.png)

**Comment by mkoch227** [comment]
This should be a pretty simple feature to implement. My only concern is the possibility of [XSS attacks](https://www.owasp.org/index.php/Cross-site_Scripting_%28XSS%29); however PHP's [`htmlspecialchars`](http://php.net/htmlspecialchars) *should* take care of it. I'm adding it to the v2.0.0 milestone.

**Comment by bastiaanc** [comment]
Hi Mike,

It would be just perfect if this can be an option.

The reason is that we have customers that only open their mail in plain text for security reasons :-(
So if it would be an option in settings it would just be perfect :-)
I don't know if this makes it to complicated?
