### ISSUE TITLE
Show creation date of ticket in admin main page

### ISSUE THREAD

**Issue by bastiaanc** [mkoch227/Mods-for-HESK#107]
Is it possible to add "creation date" additionally?

open inc/ticket_list.inc.php

Find (Around 338)

    <td class="$color">$ticket[lastchange]</td>

Change it to

Code: Select all
    <td class="$color">$ticket[dt]</td>

Also find (Around 429)

    <th class="admin_white" style="text-align:left; white-space:nowrap;"><a href="<?php echo $href . '?' . $query . $sort_possible['lastchange'] . '&amp;sort='; ?>lastchange"><?php echo $hesklang['last_update']; ?></a></th>

Change it to

    <th class="admin_white" style="text-align:left; white-space:nowrap;"><a href="<?php echo $href . '?' . $query . $sort_possible['dt'] . '&amp;sort='; ?>dt"><?php echo $hesklang['created_on']; ?></a></th>

in order to make it an additional one it should be:

Open inc/ticket_list.inc.php
find (around line 316)

    $ticket['lastchange']=hesk_time_since(strtotime($ticket['lastchange']));

Paste this just below

    $ticket['dt']=hesk_formatDate($ticket['dt']);

**Comment by mkoch227** [comment]
This feature will be part of HESK 2.6.0, so it would be pointless to add it into Mods for HESK as it will be removed when 2.6.0 is released.

![Screenshot](https://cloud.githubusercontent.com/assets/333430/5616557/95b9ad96-94d3-11e4-8f7d-c0a0b4b9f78f.png)
