### ISSUE TITLE
Request: additional email textfield like carbon copy

### ISSUE THREAD

**Issue by tutuldok** [mkoch227/Mods-for-HESK#111]
Sir can I request for an update or script that will create another text field for carbon copy email address of the requestor/customer?

Also, may I ask if there is a way in which I can notify customers once the ticket is resolved?

Thanks in advance.

**Comment by mkoch227** [comment]
HESK currently has a setting that allows customers to enter a comma-separated list of emails, rather than just one. Would that work for your situation?

As of 1.6.0, Mods for HESK will email the customer when the ticket is resolved.

**Comment by tutuldok** [comment]
Sir I already know about what you are saying "comma-separated list of emails and it is currently working on my HESK. But our customer is requesting to create a separate text field for the carbon copy email. Because they wanted to make it clear to the "Requester" that they have to notify their head every time that they are requesting for a support. That was the situation here in our office.

Regarding on the "resolved issue", I'm still testing it. Hoping that your right.. LOL

I'm hoping that you will help me on my issue so that I can now use HESK in our company.

**Comment by tutuldok** [comment]
Sir regarding on the resolve issue, I already test it and still once you ticked or selected the Mark as Resolved there is no email sent to the customer saying that the ticket has been resolved.

For my testing, I still have to reply on it telling the customer that the ticket was already resolved.

Is there a way that once the helpdesk ticked the Mark as Resolved it will automatically emailed the customer?

Thanks in advance..

**Comment by mkoch227** [comment]
I just ran a test on my production instance, and an email was sent to me when I marked my ticket as "closed"/"resolved". Where are you trying this test at? Is it on a installation you have setup?

**Comment by tutuldok** [comment]
I'm testing it on my localhost and I'm using the default version of Hesk. I didn't use any updates because my client wanted the design of it.

How am I going to retain the design while updating its version so that all of your updates and functionalities will work on it? Is it possible???

**Comment by mkoch227** [comment]
Unfortunately you will not be able to use the updates and features Mods for HESK provides while keeping the original HESK design, unless you modify the UI of Mods for HESK on your own.

**Comment by tutuldok** [comment]
ah I see. Anyways, I would like to go back on my first issue regarding on the additional text field for the CC Email. Is it possible? Can you give me the script for this? Thanks Mate

**Comment by mkoch227** [comment]
What I *can* do is create a new custom field type known as "Email". It would act as a regular text field; however, when sending emails, it'll look at custom fields that are "email" and add them to the To, Cc, or Bcc depending on the setting.

I can't give an ETA of when the feature would be rolled out though, as I'm currently placing most of my efforts on getting Mods for HESK ready for 2.6.0. Additionally, classes are starting on Tuesday, so the amount of time I'll have to work on this will decrease dramatically.

**Comment by tutuldok** [comment]
okay thanks mate! I'll just wait for your updates in the future. As of this moment, I'll just try to experiment on how will I make run this issue.
