### ISSUE TITLE
HELP: Email Custom Field

### ISSUE THREAD

**Issue by tutuldok** [mkoch227/Mods-for-HESK#116]
Sir I already tried to add CC email field and it is now inserting on the database. My only issue is the cc field is not sending only the email field is sending.

error: Note: Could not send email notifications. Please notify webmaster

here's my code: email_functions.inc.php

	// Uncomment for debugging
	# echo "<p>TO: $to<br >SUBJECT: $subject<br >MSG: $message</p>";
	# return true;
	
		$ccemail = $ticket['ccemail']; <------this is the cc field session??

    // Use PHP's mail function
	if ( ! $hesk_settings['smtp'])
    {
    	// Set additional headers
		$headers = "From: $hesk_settings[from_header]\n";
		$headers.= "Reply-To: $hesk_settings[from_header]\n";
		$headers.= "CC: " . $ccemail . "\n"; <------this is the cc field to be sent
		$headers.= "Return-Path: $hesk_settings[webmaster_mail]\n";
		$headers.= "Date: " . date(DATE_RFC2822) . "\n";
		$headers.= "Content-Type: text/plain; charset=" . $hesklang['ENCODING'];

		// Send using PHP mail() function
        ob_start();
		mail($to,$subject,$message,$headers);
        $tmp = trim(ob_get_contents());
        ob_end_clean();

        return (strlen($tmp)) ? $tmp : true;
    }

I don't know if this is where to include it. It's just a test.

Hope you'll help me with this issue.

Thanks mate!

**Comment by mkoch227** [comment]
After `$ccemail = $ticket['ccemail'];` on a new line, add `die(var_dump($ccemail));`. This will halt execution and will display the current value of `$ccemail` on the screen. This way you can double-check the actual value for `ccemail` is being properly transformed. This is purely for debugging purposes. This will also prevent HESK from trying to send the email.

I'll check back here in about 6-8 hours to see if my recommendation helps or if you got it working; it's 1:00 AM here and it's time for me to get some sleep :grinning:

**Comment by tutuldok** [comment]
I tried it already and it prompts null. So I decided to recode it and replace it with this $ccemail = $_POST['ccemail'];. 

Result: string 'xxxxxxx@xxxxxxxxxx' (length=28).

It means that it has a value right?

But after removing die(var_dump($ccemail));, I'm still getting this error: Note: Could not send email notifications. Please notify webmaster and only the to: email field was sent.

I'm really having a hard time on this, I think my head is going to blast! LOL..

I hope you'll help me with this issue. Thanks again mate!

**Comment by mkoch227** [comment]
Yes, that means there is a value in `$ccemail`. Are you using SMTP or PHP's `mail()` function to send the message?

**Comment by tutuldok** [comment]
I'm using SMTP.

**Comment by mkoch227** [comment]
Ok. Well first off, it looks like you edited the section for PHP mail (the `if` block where you added the Cc header is used for PHP mail, not SMTP). Look for `// Send the e-mail using SMTP` in `email_functions.inc.php`, and you'll find the headers a few lines lower.

Also turn on debug mode as the errors should appear if the email fails to send, so we can see the actual error, rather than a vague "email could not be sent" message.

**Comment by tutuldok** [comment]
Ah I see.. I can't see any headers on it.

Here's the code:

// Send the e-mail using SMTP
    $to_arr = explode(',',$to);
	if ( ! $smtp->SendMessage($hesk_settings['noreply_mail'], $to_arr, array(
				"From: $hesk_settings[from_header]",
				"To: $to",
                "Reply-To: $hesk_settings[from_header]",
                "Return-Path: $hesk_settings[webmaster_mail]",
				"Subject: " . $subject,
				"Date: " . date(DATE_RFC2822),
                "Content-Type: text/plain; charset=" . $hesklang['ENCODING']
			), $message))
    {
		// Suppress errors unless we are in debug mode
		if ($hesk_settings['debug_mode'])
		{
			$error = $hesklang['cnsm'] . ' ' . $to . '<br /><br />' .
					 $hesklang['error'] . ': ' . htmlspecialchars($smtp->error). '<br /><br />' .
					 '<textarea name="smtp_log" rows="10" cols="60">' . ob_get_contents() . '</textarea>';
			ob_end_clean();
			hesk_error($error);
		}
        else
        {
			$_SESSION['HESK_2ND_NOTICE']  = true;
            $_SESSION['HESK_2ND_MESSAGE'] = $hesklang['esf'] . ' ' . $hesklang['contact_webmsater'] . ' <a href="mailto:' . $hesk_settings['webmaster_mail'] . '">' . $hesk_settings['webmaster_mail'] . '</a>';
        }
    }

    ob_end_clean();

	return true;

} // END hesk_mail()

**Comment by mkoch227** [comment]
The headers are right in the snippet you gave me:

````php
"From: $hesk_settings[from_header]",
"To: $to",
"Reply-To: $hesk_settings[from_header]",
"Return-Path: $hesk_settings[webmaster_mail]",
"Subject: " . $subject,
"Date: " . date(DATE_RFC2822),
"Content-Type: text/plain; charset=" . $hesklang['ENCODING']

**Comment by tutuldok** [comment]
so what is the right code for the Cc mail? Where am I going to include it?

**Comment by mkoch227** [comment]
Do the same thing as you did previously, but add in this collection of headers, so it'll look something like:

````php
"From: $hesk_settings[from_header]",
"To: $to",
"Cc: $ccemail",
"Reply-To: $hesk_settings[from_header]",
"Return-Path: $hesk_settings[webmaster_mail]",
"Subject: " . $subject,
"Date: " . date(DATE_RFC2822),
"Content-Type: text/plain; charset=" . $hesklang['ENCODING']

**Comment by tutuldok** [comment]
"Cc: $ccemail", or "Cc:" . $ccemail ?

I'll just test it both and I'll get back to you if what is the result. Thanks!

**Comment by tutuldok** [comment]
Both codes are right.

Cc: email is already included on the mail that I received on the To: email.

But upon checking on my 2nd account in which I included it on Cc there is still no mail received.

And also I'm still receiving this error (Note: Could not send email notifications. Please notify webmaster).

What do you think is the main problem with this?

**Comment by mkoch227** [comment]
Double-check your Cc's spam folder to see if it ever actually appeared. 

Again, for the error notice, turn on debug mode. If an error occurs, you should be sent to the error page with the entire SMTP log.

**Comment by tutuldok** [comment]
Error:

Cound not send the message to: you@me.com

Error: 554 5.7.1 <you@me.com>: Relay access denied

Resolving SMTP server domain "mail.theorchardgolf.com"...
Connecting to host address "122.3.252.114" port 25...
Connected to SMTP server "mail.theorchardgolf.com".
S 220 sea.theorchardgolf.com ESMTP Sophos Email Appliance v3.8.0.3
C EHLO 128.168.64.20
S 250-sea.theorchardgolf.com
S 250-PIPELINING
S 250-SIZE 10485760
S 250-ETRN
S 250-ENHANCEDSTATUSCODES
S 250-8BITMIME
S 250 DSN
C MAIL FROM:<support@domain.com>
C RCPT TO:<you@me.com>
C DATA
S 250 2.1.0 Ok
S 554 5.7.1 <you@me.com>: Relay access denied
Disconnected.


I'm using wamp server and also our mail server address. Do I need to use gmail when using SMTP?

**Comment by mkoch227** [comment]
I'm not sure what happened to the log you provided (I saw it and then the next minute it was gone), but a 554 error code (according to [this site](https://www.penpublishing.com/Support/EmailErrors/UnderstandingEmailErrors/#554)) indicates that your mail server rejected the email address listed as the "From" email. This is most likely a server-side issue. Does this same error occur if you use a clean HESK install?

**Comment by tutuldok** [comment]
Sir I already resolved the problem. Thanks for the help..

**Comment by mkoch227** [comment]
Awesome. Glad to hear you got everything working :grinning:
