### ISSUE TITLE
Multiple custom fields

### ISSUE THREAD

**Issue by tutuldok** [mkoch227/Mods-for-HESK#117]
Sir I'm trying to put 3 select box custom fields but only 1 select box custom fields is appearing.

Note: I put an id in 1 of the select box because I included some javascript on it.

I tried 1 of the select box after the message and it appears but if I'll put it on the before the message it doesn't show.

Is it possible to have multiple select box or any same custom fields before the message?

**Comment by mkoch227** [comment]
I was able to create three select dropdown fields and they appeared without any problems on my end (both customer-side and staff-side). I don't think setting a custom id would affect it; however try removing it and see if it fixes it.

**Customer Side**
![customerside](https://cloud.githubusercontent.com/assets/333430/5850835/82bcc4fe-a1ca-11e4-95e5-60af9ee66aaa.PNG)

**Staff Side**
![staffside](https://cloud.githubusercontent.com/assets/333430/5850836/82bdbbac-a1ca-11e4-8fc7-11d6614ab422.PNG)

**Comment by tutuldok** [comment]
Sir I found out if what is the problem on it.

Because I included some style="display:none" on the select box custom fields coding.

I included style because our client wanted to hide first the 2nd select box and once the specific Category on the 1st select box is selected it will show.

Did you get what I'm trying to say? LOL

What do you think is the best solution on this? Because I will be adding select boxes in every category. haizt.....

**Comment by mkoch227** [comment]
Can I take a look at the Javascript you're using to display/hide the fields?

**Comment by mkoch227** [comment]
Issue closed due to inactivity. If you still need assistance, please re-open the issue.
