### ISSUE TITLE
Can't execute SQL on this branch

### ISSUE THREAD

**Issue by ingenuitor** [mkoch227/Mods-for-HESK#121]
Are you able to provide a full MySQL dump of a perfect setup based on the current branch for a working site. I can't submit any tickets and I did follow the steps three times with the same result, just to make sure I was not missing anything. If I had that raw SQL file I would know for sure if it's something else. 

I did a full compare of all files and that are a dead on match and tried to instal the main build with the same results. 

This is my error when trying to submit a ticket, everything else seems to work correctly and very well thought out. 

Error:

Can't execute SQL
Please notify webmaster at

Using https://github.com/mkoch227/Mods-for-HESK/tree/master-2-6-0

**Comment by mkoch227** [comment]
First off, I have a few questions:

1. What version of HESK are you using?
2. Did you follow the installation instructions?

The `master-2-6-0` branch is a pre-release branch and isn't supported for production use at this time. Also turn on debug mode, so you (and I) can see the query that is failing and what the error is.

**Comment by ingenuitor** [comment]
Hello, thanks for such a quick response.

Here are the setup specs, which I did follow closely a few times over.

Installation Information
HESK version:	2.6.0 beta 1
Mods for HESK Version:	1.7.0
PHP version:	5.2.17 (MySQLi)
MySQL version:	5.0.95-community
/hesk_settings.inc.php	Exists, Writable
/attachments	Exists, Writable

Here is the debug, which seems like an SQL issue, can I again get the raw dump, then I'm sure I have a clean slate or the missing SQL to resolve this issue?

Error:

Can't execute SQL: SELECT `t1`.`id`,`t1`.`user`,`t1`.`name`, `t1`.`email`, `t1`.`language`, `t1`.`isadmin`, `t1`.`categories`, `t1`.`notify_assigned`, `t1`.`heskprivileges`, (SELECT COUNT(*) FROM `helpdesk_tickets` FORCE KEY (`statuses`) WHERE `owner`=`t1`.`id` AND `status` IN ('0','1','2','4','5') ) as `open_tickets` FROM `helpdesk_users` AS `t1` WHERE `t1`.`autoassign`='1' ORDER BY `open_tickets` ASC, RAND()
MySQL said:
Key 'statuses' doesn't exist in table 'helpdesk_tickets'
 
WARNING
Debug mode is enabled. Make sure you disable debug mode in settings once HESK is installed and working properly.

Thanks again, great work you are doing here, I will look to see how I can contribute.  I have looked at many many other help systems, and thus far this one seems to be firming up to be a clean solution in the open source non cloud version world.

**Comment by mkoch227** [comment]
The missing key issue was reported once before by someone else, but I was never able to reproduce it yet. However, it seems that the key will need to be added to the table.  I'm not 100% sure on the MySQL syntax to do that (I'm used to MSSQL), but it should be relatively straightforward.

**Comment by mkoch227** [comment]
@ingenuitor : Can you run the following query for me, and see if you get any results?

````sql
SHOW KEYS FROM helpdesk_tickets WHERE Key_name='statuses`

**Comment by ingenuitor** [comment]
@mkoch227:

Your SQL query has been executed successfully ( Query took 0.0016 sec ) I can see those tables are in place, here is the dump.

-- phpMyAdmin SQL Dump
-- version 3.4.9
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jan 24, 2015 at 10:31 AM
-- Server version: 5.0.95
-- PHP Version: 5.2.6

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `aws_help`
--

-- --------------------------------------------------------

--
-- Table structure for table `helpdesk_statuses`
--

CREATE TABLE IF NOT EXISTS `helpdesk_statuses` (
  `ID` int(11) NOT NULL,
  `ShortNameContentKey` text NOT NULL,
  `TicketViewContentKey` text NOT NULL,
  `TextColor` text NOT NULL,
  `IsNewTicketStatus` bit(1) NOT NULL default b'0',
  `IsClosed` bit(1) NOT NULL default b'0',
  `IsClosedByClient` bit(1) NOT NULL default b'0',
  `IsCustomerReplyStatus` bit(1) NOT NULL default b'0',
  `IsStaffClosedOption` bit(1) NOT NULL default b'0',
  `IsStaffReopenedStatus` bit(1) NOT NULL default b'0',
  `IsDefaultStaffReplyStatus` bit(1) NOT NULL default b'0',
  `LockedTicketStatus` bit(1) NOT NULL default b'0',
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `helpdesk_statuses`
--

INSERT INTO `helpdesk_statuses` (`ID`, `ShortNameContentKey`, `TicketViewContentKey`, `TextColor`, `IsNewTicketStatus`, `IsClosed`, `IsClosedByClient`, `IsCustomerReplyStatus`, `IsStaffClosedOption`, `IsStaffReopenedStatus`, `IsDefaultStaffReplyStatus`, `LockedTicketStatus`) VALUES
(0, 'open', 'open', '#FF0000', '', '\0', '', '', '', '', '', ''),
(1, 'wait_reply', 'wait_staff_reply', '#FF9933', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0'),
(2, 'replied', 'wait_cust_reply', '#0000FF', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0'),
(3, 'resolved', 'resolved', '#008000', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0'),
(4, 'in_progress', 'in_progress', '#000000', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0'),
(5, 'on_hold', 'on_hold', '#000000', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

**Comment by mkoch227** [comment]
I'm not intersted in the actual table setup; I'm curious if the `statuses` key exists in the `tickets` table

**Comment by mkoch227** [comment]
The 2.0.0 update script now contains the SQL needed to add the missing key if it does not exist already.
