### ISSUE TITLE
Fontawesome CSS

### ISSUE THREAD

**Issue by tutuldok** [mkoch227/Mods-for-HESK#125]
Sir i'm trying to direct my Fontawesome.css locally like <link href="css/font-awesome.css" rel="stylesheet"> not using this <link href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.css" rel="stylesheet">.

My problem is some of the icons are missing especially on this page "manage_users.php"; icons under OPTIONS.

I tried the latest version of Fontawesome 4.3 and also 4.2 but still icons are missing.

I'm using Hesk locally so I wanted my page to load faster that's why I changed the script.

I'm still exploring the site if it still affect some page.

Hoping for your kindest help and response.

Thanks!

**Comment by mkoch227** [comment]
Are you still having a problem? I see you self-closed your issue; however I wanted to double-check

**Comment by tutuldok** [comment]
I already resolved it buy putting "../". But I'm still currently testing
and exploring it. I'll give you feedback once my issue still occurs.

Anyways, thanks for the immediate response mate!




Thanks,
*Wilfredo R. Crucena Jr.*
MIS-IT Specialist
The Orchard Golf and Country Club
