### ISSUE TITLE
Mailgun Support

### ISSUE THREAD

**Issue by coinwall** [mkoch227/Mods-for-HESK#126]
Hello,

I write to standart hesk possibility to send mail's via mailgun api, to protect real IP of my server.

Do you can merge this with mods ?
I modified inc/email_functions.inc.php and i can give you that file.

Cheers
Coinwall

**Comment by mkoch227** [comment]
If you would like to share the file with me, that's fine. Feel free to email it to me or upload the file as a [GitHub Gist](https://gist.github.com/)

**Comment by coinwall** [comment]
Thanks for fast replay.
I send to you file via email.

Cheers
