### ISSUE TITLE
Can't receive mail using PHP Mail instead of SMTP

### ISSUE THREAD

**Issue by tutuldok** [mkoch227/Mods-for-HESK#129]
Sir its me again.. LOL

Sorry if I have a lot of question/issue raising to you because I'm a newbie on HESK and codings.

My question is I can't receive any email when I'm using PHP Mail instead of SMTP. I used PHP Mail because I'm using HESK locally and most of our client doesn't have internet access and their email is just INTRAMAIL. We are just using POP3 here in our company to send and receive mail.

Any solution or answer to this?

**Comment by mkoch227** [comment]
Does this issue not occur on a regular HESK 2.5.5 install? (without Mods for HESK)

**Comment by tutuldok** [comment]
I'm not yet testing on the regular HESK. But based on forums that I searched, WAMP can't send email locally or using PhpMail. SMTP is really needed, is that true?

**Comment by mkoch227** [comment]
I honestly don't know the answer to that question. However, if the problems isn't Mods for HESK related, then unfortunately I cannot be of much help here.

**Comment by mkoch227** [comment]
Perhaps this might help? http://blog.techwheels.net/send-email-using-wamp-server/

**Comment by tutuldok** [comment]
ok thanks for that!
