### ISSUE TITLE
IE Compability

### ISSUE THREAD

**Issue by pushpak359** [mkoch227/Mods-for-HESK#130]
In IE 11 and google chrome display of mods of hesk works fine but in IE 10 or below there is a displaying three line button.

**Comment by mkoch227** [comment]
Can you provide a screenshot for me?

**Comment by pushpak359** [comment]
IE 11
![10](https://cloud.githubusercontent.com/assets/10828799/6020788/1b7d9d20-abd6-11e4-8e88-47a0fe112dd7.jpg)

IE 10 and below addded menu button and alignment changes
![8](https://cloud.githubusercontent.com/assets/10828799/6020792/28d9ba26-abd6-11e4-89ce-57c902131bb4.jpg)

**Comment by mkoch227** [comment]
For the first screenshot: do you have anything in your `header.txt` file?
For the second screenshot: what is your screen resolution? The layout moves to the "mobile" view when the screen resolution goes below a width of 768px

**Comment by pushpak359** [comment]
yes, i have header.txt" i have mentioned a logo in that file.

yes its actually moves to mobile view i down know why this is happening. screen resolution is 1366 X 768.

**Comment by mkoch227** [comment]
If your header.txt file is the cause of your IE 10 vs 11 issues, check to see if the same problem occurs on a base HESK installation.

If you want to change the breakpoints of when the view switches to mobile, you will need to modify Bootstrap's LESS/SASS, which unfortunately is beyond the scope of my support.  Monitor width's of 768px are today typically the size of a large tablet, which is why it is defaulting to a mobile view

**Comment by mkoch227** [comment]
Disregard my last comment, as I see what you mean now. I'll see if I can get a VM going and see what happens on my test instance.

**Comment by mkoch227** [comment]
One more thing: can you make sure compatibility mode is **off** on IE10?

**Comment by pushpak359** [comment]
i have checked in compatibility mode off. nothing happened IE 10 and IE 8 has same issue.

**Comment by pushpak359** [comment]
hey @mkoch227 i think its a document mode issue i have added document mode default IE 9 metatag in index.php and it works fine in IE 9+ but not in IE 8.

**Comment by mkoch227** [comment]
IE 8 only has partial compatibility (as listed in the readme), as IE 8 is older and doesn't support today's HTML5 features/specifications.  Due to IE 8's age (5 years old now), I don't plan on making any fixes for it. If IE 9+ is working now, I'm going to go ahead and close out this issue.

**Comment by mhoffmann1** [comment]
hello @mkoch227 
we have this issue with internet explorer 11. The page is displayed in mobile view only. In Firefox the page works fine.
Do you have any ideas?
