### ISSUE TITLE
Verify Email URL Issue

### ISSUE THREAD

**Issue by ingenuitor** [mkoch227/Mods-for-HESK#135]
When you receive a Verify Email, you receive the following. Seemly the %%VERIFYURL%% is a bug, or is this in setup? Thanks

Your email needs to be verified before your ticket can be submitted. Please click the link below to verify your email.

%%VERIFYURL%%

Sincerely,

**Comment by mkoch227** [comment]
What version are you currently using? 1.7.0 or 2.0.0 beta?

**Comment by mkoch227** [comment]
And I just ran a test on my test instance, and it worked just fine:

> Dear Name, 
>
>Your email needs to be verified before your ticket can be submitted. Please click the link below to verify your email. 
>
>http://my domain/verifyemail.php?key=d6eaccdd7fd85c3f0dec1b3077c5311680886233511c95a315c82c08457bfb7be628c4e37b4074604b2e6c8ed046ba17e793e914c5e4e7002b8ccdc4df690223
>
>Sincerely, 
>
>My Web site

**Comment by mkoch227** [comment]
Issue closed due to inactivity. Please re-open if need be.
