### ISSUE TITLE
Attachments in emails

### ISSUE THREAD

**Issue by bastiaanc** [mkoch227/Mods-for-HESK#146]
Right now, if attachments are uploaded by the admin, the customer will receive an email wit a link, so they can download the attachment. A lot of customers really don't understand this for some reason. Is it possible to have a additional option where you can decide as an admin to attach attachments to the email instead of a link?

Thanks Mike, I hope this is not so difficult :-)

**Comment by zelenkovsky** [comment]
+1

And please attachments for Canned Responses as well.

**Comment by mkoch227** [comment]
If you can post this feature request at the Mods for HESK UserVoice page (as requested in the [contributing guidelines](https://github.com/mkoch227/Mods-for-HESK/blob/master/CONTRIBUTING.md)), it would be appreciated.

**Comment by mkoch227** [comment]
Locking this issue until request is added to the UserVoice page

**Comment by mkoch227** [comment]
I'm going to close this for now since it's on the UserVoice page. If this gets pulled in as a feature, I'll reopen this issue.

**Comment by mkoch227** [comment]
Re-opening as it is planned for v2.2.0

**Comment by mauroagr** [comment]
Dear,
Have ideia to put this in some version?
I install the 2.2.1 and dont see this option.
Thanks
Mauro

**Comment by mkoch227** [comment]
This feature is planned for v2.2.0 (the latest released version is **2.1.1**, not 2.2.1).

**Comment by mauroagr** [comment]
Hi,
Sorry, i am a donkey..hehe.
I am trying to update the email_functions.inc.php to make this.
I am not a big github user, but if i get sucess, i send the update to you.
Thanks
Mauro

**Comment by mkoch227** [comment]
Haha that's ok :grinning:. Best of luck on getting it to work! This issue is next on my list after I finish #153.

**Comment by mauroagr** [comment]
When i have the old hesk version, i dont have sucesso to configure with headers the attached.
Then i put the phpmailer, and change all...was running fine..fine.
When i update, crash all...hehehehe.
Thanks
Mauro

**Comment by mauroagr** [comment]
Hi Mike,
Congrats...you make the script. I make my code using phpmailer, dont have sucess in smtp headers direct, (i was make some shit).
Thanks
Mauro
