### ISSUE TITLE
Display other tickets from the same email

### ISSUE THREAD

**Issue by zelenkovsky** [mkoch227/Mods-for-HESK#153]
It is very usefull to see the list of last 5-10 tickets from the same email in chronological order from the Ticket Admin view.

In hesk/admin/admin_ticket.php?track=XXXXXX

Usually operator requires to see other tickets for the same person in order to assist with current issue in the most efficient way.

**Comment by extremeshok** [comment]
+1

Also allow the operator to merger to current ticket to a previous one.

**Comment by mkoch227** [comment]
If you can post this feature request at the Mods for HESK UserVoice page (as requested in the [contributing guidelines](https://github.com/mkoch227/Mods-for-HESK/blob/master/CONTRIBUTING.md)), it would be appreciated.

**Comment by mkoch227** [comment]
Locking this issue until request is added to the UserVoice page

**Comment by mkoch227** [comment]
I'm going to close this for now since it's on the UserVoice page. If this gets pulled in as a feature, I'll reopen this issue.

**Comment by mkoch227** [comment]
Re-opening as part of v2.2.0
