### ISSUE TITLE
Re-package mods-for-hesk released

### ISSUE THREAD

**Issue by extremeshok** [mkoch227/Mods-for-HESK#154]
It would be far easier and better if the mods for hesk included hesk.

So we do not need to first download hesk, install, patch, install mods for hesk

ie. user downloads 1 file and installs it and runs the installer.
or the user can just github clone and run the installer.

**Comment by zelenkovsky** [comment]
+1 agree.

**Comment by mkoch227** [comment]
I would, however it is against Klemen's terms to do so. Until the foreseeable future, this is how it needs to be.
