### ISSUE TITLE
Make some statuses "non-closeable"

### ISSUE THREAD

**Issue by PeopleInside** [mkoch227/Mods-for-HESK#157]
Hi,
in original Hesk i had edited ticket.php where from line 565 you have a list of ticket status with near  $close_link; so you can remove this in the status where you don't want customer can close ticket.

This is userfull when you want customer able to close when ticket is new or with reply by staff but not when is on Hold on in Progress.

Seems with MOD you can't do this edit.. i can't find the sdame line so you can only alow customer or not in all status. 

Can you implement the possibility to decide near each stastus if there are or not close button? Can you find a solution please?
Maybe have the code in ticket.php who alow this if you won't implemented in grafic admin panel.
Thanks.

**Comment by mkoch227** [comment]
If you can post this feature request at the Mods for HESK UserVoice page (as requested in the [contributing guidelines](https://github.com/mkoch227/Mods-for-HESK/blob/master/CONTRIBUTING.md)), it would be appreciated.  This way other users can vote on the issue rather than saying "+1", "-1" etc.

**Comment by PeopleInside** [comment]
Done, thanks
https://mods-for-hesk.uservoice.com/forums/254758-general/suggestions/7164042-alow-user-to-close-ticket-only-in-some-status-ple

**Comment by mkoch227** [comment]
I'm going to close this for now since it's on the UserVoice page. If this gets pulled in as a feature, I'll reopen this issue.

**Comment by mkoch227** [comment]
Reopening as part of 2.2.0

**Comment by mkoch227** [comment]
Completed in PR #192 and will be released in v2.2.0.
