### ISSUE TITLE
Issue Lost ticked ID HTML Email

### ISSUE THREAD

**Issue by PeopleInside** [mkoch227/Mods-for-HESK#158]
Hi,
if HTML mail are disabled all seems to work fine.

If HTML email is enable when user request id of the opened ticket
in the HTML email 

%%LIST_TICKETS%% 

will be replaced by Ticket Subject, Prority, and link all this information is on the same row so very confusing.

In non HTML every data are ordined for row.

You have to reproduce the same in HTML mail forgot ticked id, i have tried with one opened ticket and information are confuse because is all in the same row.

**This is bug for me,
need to be fixxed.**

**Comment by PeopleInside** [comment]
Thanks, how i can be notified about new relase? In Hesk settings i can see the current version of MOD but i don't see like hesk if is updated or not. Maybe i have try to request this feature to? There is a way to be notified when the new version will be relased? Thanks.

**Comment by mkoch227** [comment]
When a new version of HESK is released, I will post a topic on the PHP Junkyard forums indicating there is a new release.

I also plan to add an update-checking system (similar to HESK's in Mods for HESK 2.1.0)

**Comment by PeopleInside** [comment]
So no way for now to be notified by email about update. If i had no problem i don't go on PHP Junkyard forums . Thanks
