### ISSUE TITLE
admin/new_ticket.php Manage template ticket should open in a new window

### ISSUE THREAD

**Issue by PeopleInside** [mkoch227/Mods-for-HESK#167]
Manage ticket templates link should open in a new window because if user has already compiled the ticket and click on that link is impossibile to resume the previous work, all data inserted into ticket are lost. Operator can use back button but on SSL where I'M all text are to recompile from the start so URL should be in new window.

**Comment by mkoch227** [comment]
This is consistent with the default version of HESK, and therefore is not a bug. Please send this to the [UserVoice page](https://mods-for-hesk.uservoice.com/).

**Comment by PeopleInside** [comment]
Sorry i can't. No mre point to vote. Thanks for your feedback. IT's ok for me now i will know. thanks.

**Comment by mkoch227** [comment]
Since many of the suggestions on the UserVoice page are marked as "Planned", feel free to remove your votes from those and re-use them elsewhere, as they are going to be included, regardless on the number of votes :grinning:

**Comment by PeopleInside** [comment]
Done, thanks https://mods-for-hesk.uservoice.com/forums/254758-general/suggestions/7211417-admin-new-ticket-php-manage-template-ticket-should Happy to see planned ideas.
