### ISSUE TITLE
Knowledge Base / Private or Public

### ISSUE THREAD

**Issue by bastiaanc** [mkoch227/Mods-for-HESK#170]
Right now, if a knowledge base article or category is made, the standard view is "public"

I mentioned it, again and again, to my co-workers (but they keep forgetting) to put the articles (or also categories) on private.

Because of their behavior we had passwords for social media accessible for everybody looking in the knowledge base.

Now could the knowledge base be changed in a way that if you create an article or category that the standard view is "private"
It is better to change it to "public" then forgetting it to put on "private"

Thanks so much for everything you do :-)

**Comment by mkoch227** [comment]
This "feature request" should be submitted to the [UserVoice page](http://mods-for-hesk.uservoice.com) (I will most likely marked it as "planned" immediately.

**Comment by bastiaanc** [comment]
Right now, if a knowledge base article or category is made, the standard view is "public"

I mentioned it, again and again, to my co-workers (but they keep forgetting) to put the articles (or also categories) on private.

Because of their behavior we had passwords for social media accessible for everybody looking in the knowledge base.

Now could the knowledge base be changed in a way that if you create an article or category that the standard view is "private"
It is better to change it to "public" then forgetting it to put on "private"

Thanks so much for everything you do :-)

**Comment by bastiaanc** [comment]
Did that

**Comment by mkoch227** [comment]
Thanks!
