### ISSUE TITLE
URL issue on HTML email

### ISSUE THREAD

**Issue by PeopleInside** [mkoch227/Mods-for-HESK#171]
URL are not clicable if the email is receved in Thunderbird because they has not the atribute <a>
i tried to put into email language file but not seems to solve the issue.

**Comment by mkoch227** [comment]
Do you mean the link for your help desk's URL? (%%SITE_URL%%). What happens if you try
`<a href="%%SITE_URL%%">%%SITE_URL%%</a>`?

**Comment by PeopleInside** [comment]
Tested, seems to not work.
URL are not clickable.

**Comment by mkoch227** [comment]
I'm currently unable to access my SMTP server right now so I can't test any emails for a few hours. Would you mind forwarding me one of your emails (with the `<a>` tag added) to mkoch227 [at] gmail [dot] com so I can take a look at it?

**Comment by PeopleInside** [comment]
Done. You should receve shortly.

**Comment by mkoch227** [comment]
Ok I got the email. It looks like there is an `<a>` tag in the plaintext template; however I don't see any `<a>` tag at all on the HTML side. Are you sure you added the `<a>` tag to the template in the `/html` directory?

**Comment by PeopleInside** [comment]
Sorry but not good idea past here my header code where also there are my email address so please remove it also in pastebin. Some data are private that why need shared only by email.
Thanks for understanding.

I think to have edited the content inside html pretty sure but i can test again and i will send the email and the file via email.
I will do this now.

**Comment by mkoch227** [comment]
Ok that's fine. And I removed the pastebin links.

**Comment by PeopleInside** [comment]
Please remove also from pastebin thanks. I will check later, i don't like my headers are pasted on the internet.
Thanks for removing links.

I had sended other email. I had made all correct as i can see and i had tested again, result it's the same. No clickable URL.

**Comment by PeopleInside** [comment]
I hope HTML mail can have correct link attribute or some user when receve email can't click the link. This is not wonderful to see.

I had also contacted Thunderbird but they say HTML email must be formatted correctly is not a Thunderbird issue.

I will see in this day if here can found a solution. I wait.
Thanks ^_^

HTML are great. I think this should be the last think to fix.
URL should be always clickable.

**Comment by mkoch227** [comment]
Ok I think I came up with a solution:  all HTML emails will have link tags (`<a>`) wrapped around text that appears to be a link automatically, so you should not have to add `<a>` tags around certain elements.  This will be part of v2.2.0
