### ISSUE TITLE
Update code for HESK 2.6.2

### ISSUE THREAD

**Issue by mkoch227** [mkoch227/Mods-for-HESK#174]

**Comment by PeopleInside** [comment]
So is better wait the new relase 2.2.0 of Mod Hesk before update Hesk to the new version? 

If the reply is yes, you suggest to update before Mod for Hesk and after Hesk or what? 
Thanks

**Comment by mkoch227** [comment]
The only change to 2.6.2 was a fix in the export tickets feature, as described on [the forums](http://developers.phpjunkyard.com/viewtopic.php?f=13&t=5038). If you are experiencing this issue, you can apply the diffs manually as described [here](http://developers.phpjunkyard.com/viewtopic.php?f=13&t=5234).

Once Mods for HESK 2.2.0 is released, the installation instructions on the Mods for HESK [website](http://mods-for-hesk.mkochcs.com) will be updated to describe what the upgrade process will be.

**Comment by PeopleInside** [comment]
Thanks!
