### ISSUE TITLE
Show Reply Form at Bottom is Mis-Aligned

### ISSUE THREAD

**Issue by mkoch227** [mkoch227/Mods-for-HESK#175]
The replies are rendered in the submit button's `form-group` element, rather than a separate container.

![schermafbeelding 2015-03-20 om 14 02 41](https://cloud.githubusercontent.com/assets/333430/6763247/17a36df4-cf4b-11e4-8e30-2476e5c19c2c.png)

**Comment by bastiaanc** [comment]
Thanks so much Mike. Really appreciate you took care of this :-)
