### ISSUE TITLE
In-line image attachments overflow the container

### ISSUE THREAD

**Issue by mkoch227** [mkoch227/Mods-for-HESK#176]
The `max-width` property is missing in `.file-attachment > img` to restrict the width to the container.

![schermafbeelding 2015-03-20 om 14 11 45](https://cloud.githubusercontent.com/assets/333430/6763261/64094560-cf4b-11e4-8cac-ddf84eb31753.png)

**Comment by bastiaanc** [comment]
Mike, I tried to implemet this, but the little had (to click) is gone and the image is still going overthe container?

**Comment by mkoch227** [comment]
Add a semicolon (`;`) after the `max-width` property. Your browser might not be as forgiving as mine :wink:

**Comment by bastiaanc** [comment]
Still is not looking good :-(

**Comment by mkoch227** [comment]
What browser (including version) are you currently using?

**Comment by bastiaanc** [comment]
Firefox 
![schermafbeelding 2015-03-22 om 21 34 23](https://cloud.githubusercontent.com/assets/9219295/6771274/423653f6-d0db-11e4-8a8a-f25539b210f2.png)

**Comment by bastiaanc** [comment]
Chrome
![schermafbeelding 2015-03-22 om 21 37 14](https://cloud.githubusercontent.com/assets/9219295/6771290/a4b778ca-d0db-11e4-97b9-03c1d4dab455.png)

**Comment by mkoch227** [comment]
Ok, it looks like a windows size issue. I'll have to rethink how to fit this image in.

**Comment by bastiaanc** [comment]
I see it now ;-) Because I have a 27" screen I only use half of the screen. That is why I did not saw that :-)

**Comment by bastiaanc** [comment]
I almost forgot to thank you for the new look of the attachments. I am sure it took you some time to figure out how it would fit best.
It looks so much better then before. We really it :-) !!!! Thanks for all the time that you have put in this!
