### ISSUE TITLE
Profile for normal admin

### ISSUE THREAD

**Issue by bastiaanc** [mkoch227/Mods-for-HESK#181]
If I am the "God Admin", I am allowed to change the profile items for other non "God Admins":
- Select notify customer option in the new ticket form
- Select notify customer option in the ticket reply form

![screen shot 2015-03-23 at 9 46 34 am](https://cloud.githubusercontent.com/assets/9219295/6776717/78c60f08-d142-11e4-9c0d-10333c815902.png)

However, the "non God Admins" can not change it themselves in their own profiles

Also the "non God Admins" can not change "Ticket Table Auto-Refresh" in their own profile.
![screen shot 2015-03-23 at 9 55 43 am](https://cloud.githubusercontent.com/assets/9219295/6776771/f688406e-d142-11e4-84a7-4db3123d5211.png)

**Comment by mkoch227** [comment]
The problem appears to be specific to the Profile page as it affects all users. Working on the fix now.

**Comment by mkoch227** [comment]
However I'm not able to reproduce the auto-refresh issue. I was able to update all autorefresh values on the profile page and the manage_users page without any issues for any user.
