### ISSUE TITLE
Auto-assign tickets to this user & Can manage help desk settings

### ISSUE THREAD

**Issue by bastiaanc** [mkoch227/Mods-for-HESK#182]
When I add a new user or edit it is just not appearing.
![screen shot 2015-03-23 at 10 00 02 am](https://cloud.githubusercontent.com/assets/9219295/6776866/3deee754-d144-11e4-9c06-c4b83884ac09.png)

**Comment by mkoch227** [comment]
Run this SQL query, and send me back the results:
```sql
SELECT `id`, `user`, `can_manage_settings` WHERE `user` = '<your username here>'`
```

**Comment by bastiaanc** [comment]
How do I do that.
??
Click on sql and put it in?
Sorry, .. ;-(

**Comment by mkoch227** [comment]
Correct

**Comment by bastiaanc** [comment]
SQL-query: Documentatie

SELECT `id`, `user`, `can_manage_settings` WHERE `user` = '<bret>'`

MySQL meldt: Documentatie
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `user` = '<bret>'`' at line 1

**Comment by mkoch227** [comment]
In the query I gave you, replace `<your username here>` with **your** HESK username

**Comment by bastiaanc** [comment]
SQL-query: Documentatie

SELECT id, user, can_manage_settings WHERE user = ''`

MySQL meldt: Documentatie
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE user = ''`' at line 1

**Comment by bastiaanc** [comment]
SQL-query: Documentatie

SELECT id, user, can_manage_settings WHERE user = 'admin'`

MySQL meldt: Documentatie
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE user = 'admin'`' at line 1

**Comment by mkoch227** [comment]
Whoops. Try this:

```sql
SELECT `id`, `user`, `can_manage_settings` from `hesk_users` WHERE `user` = 'admin'
```

**Comment by bastiaanc** [comment]
Weergave van records 0 - 0 (1 totaal, Query duurde 0.0004 seconden.)

**Comment by mkoch227** [comment]
Can you show me the records that show up after executing the query?

**Comment by bastiaanc** [comment]
Can you login the php admin please?
I have sent the login to you

**Comment by mkoch227** [comment]
The username / password combination you sent me is not working for me. See email.

**Comment by bastiaanc** [comment]
can you try now. I did a reset

**Comment by mkoch227** [comment]
Ok it worked. I can see the setting right now:


![untitled](https://cloud.githubusercontent.com/assets/333430/6790283/f3e394e6-d17c-11e4-8c10-c0f5ed6b02d7.png)

**Comment by bastiaanc** [comment]
Yes, but try it out. It has no effect after saving

**Comment by bastiaanc** [comment]
And where is auto assign tickets to this user?

**Comment by mkoch227** [comment]
Auto-assign is set to OFF on this helpdesk, so tickets are never being auto-assigned.  Also, are you sure this helpdesk is updated to 2.1.1? The settings page indicates you're running 2.1.0

**Comment by bastiaanc** [comment]
Ok, I did not understand that part.
So it is a 2.1.1 thing. I am backing up now and I am going to install it in 5 minutes. I will keep you posted :-)
Thanks

**Comment by bastiaanc** [comment]
I have updated to 2.1.1. but if I make someboody admin and unclick "can manage helpdesk settings" he still can. :-(

**Comment by mkoch227** [comment]
Heheh... this issue came back again when updating Mods for HESK to HESK 2.6.0. It's a relatively quick fix. Try making this change and see if it works: https://github.com/mkoch227/Mods-for-HESK/commit/2962d9cf3e51330c34587c42f662e380e496abaa

**Comment by bastiaanc** [comment]
YEAHHHH :-) YES!!!!!
Thanks it works !!! :-)

**Comment by mkoch227** [comment]
Woo-hoo! :grinning: Let's just hope I don't accidentally remove it again :laughing:

**Comment by bastiaanc** [comment]
Is it possible to do the same thing for tools?

**Comment by mkoch227** [comment]
After a certain point, is there a benefit of making this user an "admin"? What would happen if you chose staff  instead of administrator and checked off all categories / features besides "manage help desk settings" and the options for tools?

**Comment by bastiaanc** [comment]
My Only thing is that the users below me want to change everything without
using their brains. I can not even let people make new articles in the
knowledge base without them spreading all passwords through the world.
I know exactly what you are saying, but they feel that they are so important
that they have to be an admin.

Van:  Mike Koch <notifications@github.com>
Beantwoorden - Aan:  mkoch227/Mods-for-HESK
<reply+008cacdfbd4106c44a5a824ebafb4b505bb97e21bd7d595a92cf0000000111284dd39
2a169ce03cb87fd@reply.github.com>
Datum:  maandag 23 maart 2015 22:55
Aan:  mkoch227/Mods-for-HESK <Mods-for-HESK@noreply.github.com>
CC:  "B. Cuppen" <bas@cuppen.de>
Onderwerp:  Re: [Mods-for-HESK] Auto-assign tickets to this user & Can
manage help desk settings (#182)


After a certain point, is there a benefit of making this user an "admin"?
What would happen if you chose staff  instead of administrator and checked
off all categories / features besides "manage help desk settings" and the
options for tools?

‹
Reply to this email directly or view it on GitHub
<https://github.com/mkoch227/Mods-for-HESK/issues/182#issuecomment-85218939>
.

**Comment by mkoch227** [comment]
Gotcha. I'm thinking of adding a feature down the line that would allow for custom access groups (besides "Administrator" and "Staff"), allowing you to pre-define certain groups.  This way you can have "Global Administrator", "Some other administrative group", etc. If your staff member purely wants the "admin" title, this feature I'm thinking of may make him happy, while making it easier to manage permissions.

**Comment by bastiaanc** [comment]
That would be a just perfect solution! :-) Great idea ! :-)

**Comment by bastiaanc** [comment]
Mike, I also want to tell you that the "delete ticket" or "edit" option is also very good since we had one person that started to delete tickets before leaving the position. Can you believe that?

**Comment by bastiaanc** [comment]
Mike, I agree that we could make no admin, but if somebody makes a new category the non admins are not allowed to se the categories yet.
