### ISSUE TITLE
Footer in wrong place on ticket resolved page

### ISSUE THREAD

**Issue by PeopleInside** [mkoch227/Mods-for-HESK#186]
I had put a link with Terms and Condition in the footer file.

If i enter on my help desk admin and check resolved ticket than show i see the footer Terms and Conditions on the right top of the page, not in the footer.

Can you check if you can reproduce?
Thanks.

**Comment by mkoch227** [comment]
Can you provide a screenshot for me?

**Comment by PeopleInside** [comment]
Yes mkoch227,
for you, yes :D for sure ^_^

In all other admin page footer are at the footer but in show_tickets and resolved selected footer are not in right place.
![footer issue](https://cloud.githubusercontent.com/assets/5006150/6856700/03c69c78-d402-11e4-9266-8d4a2ca84532.png)

**Comment by mkoch227** [comment]
Hmm... I'm not able to reproduce your issue (the footer is in the correct place on `admin_main.php`). If you want to provide the contents of your `footer.txt` file, I'll see if anything looks out of the ordinary (and I'll toss the code into my instance to see if it works for me or not)

**Comment by PeopleInside** [comment]
Please can you remeber an address to send the file? Thanks

**Comment by mkoch227** [comment]
You can send it to `mkoch227@gmail.com`

**Comment by PeopleInside** [comment]
Done thanks.
