### ISSUE TITLE
Width Ticket List

### ISSUE THREAD

**Issue by bastiaanc** [mkoch227/Mods-for-HESK#194]
Can you please change the width of the ticket list? It would be helpful to use all the space to have optimal use of the relevant info. Please see attachment to see what I mean ;-)
![schermafbeelding 2015-04-11 om 09 51 30](https://cloud.githubusercontent.com/assets/9219295/7100697/c8b1bef2-e030-11e4-9841-512ab329ace0.png)

**Comment by mkoch227** [comment]
It looks like there is only a partial screenshot, which makes it hard for me to see what is going on below. Can you provide a full screenshot of what's happening?

**Comment by bastiaanc** [comment]
Hi Mike,
It is only needed to reduce the white gaps on the left and the right ;-)

Van:  Mike Koch <notifications@github.com>
Beantwoorden - Aan:  mkoch227/Mods-for-HESK
<reply+008cacdfbde45a970d5cd3c5b5b92cc75aa7d9a0cbb8d63092cf0000000111401f3b9
2a169ce0408f418@reply.github.com>
Datum:  zaterdag 11 april 2015 01:31
Aan:  mkoch227/Mods-for-HESK <Mods-for-HESK@noreply.github.com>
CC:  "B. Cuppen" <bas@cuppen.de>
Onderwerp:  Re: [Mods-for-HESK] Width Ticket List (#194)


It looks like there is only a partial screenshot, which makes it hard for me
to see what is going on below. Can you provide a full screenshot of what's
happening?


Reply to this email directly or view it on GitHub
<https://github.com/mkoch227/Mods-for-HESK/issues/194#issuecomment-91715944>
.

**Comment by mkoch227** [comment]
You mean something like this?
![capture](https://cloud.githubusercontent.com/assets/333430/7099364/fbc27ce0-dfbe-11e4-9b12-844ef50954ca.PNG)

**Comment by bastiaanc** [comment]
Yes, the space on the left and the right is not needed ;-)

Van:  Mike Koch <notifications@github.com>
Beantwoorden - Aan:  mkoch227/Mods-for-HESK
<reply+008cacdf1bc3c77254981d901fb027afa04bb04063157ea492cf0000000111402abb9
2a169ce0408f418@reply.github.com>
Datum:  zaterdag 11 april 2015 02:20
Aan:  mkoch227/Mods-for-HESK <Mods-for-HESK@noreply.github.com>
CC:  "B. Cuppen" <bas@cuppen.de>
Onderwerp:  Re: [Mods-for-HESK] Width Ticket List (#194)


You mean something like this?
 <https://cloud.githubusercontent.com/assets/333430/7099364/fbc27ce0-dfbe-11
e4-9b12-844ef50954ca.PNG>


Reply to this email directly or view it on GitHub
<https://github.com/mkoch227/Mods-for-HESK/issues/194#issuecomment-91726039>
.

**Comment by bastiaanc** [comment]
![example](https://cloud.githubusercontent.com/assets/9219295/7100712/5b26034c-e031-11e4-913d-aea865948b47.jpg)
