### ISSUE TITLE
Move Mods for HESK Settings into rest of Settings/Tools

### ISSUE THREAD

**Issue by mkoch227** [mkoch227/Mods-for-HESK#195]
- [x] Move "General" tab items into their respective tabs, indicating Mods for HESK-specific settings with `<span class="label label-primary">...</span>` prefixes
- [x] Move "Statuses" ~~and "UI Colors"~~ into Tools (_UI Colors will stay under settings_)
- [x] Remove "Long Name Content Key" from "Statuses" and drop the respective column. We're only using one key value now.

**The tab should remain on the settings page until the next minor release _v2.X.0_ indicating the move. Once the next minor release has been released, the tab will be removed**

**Comment by bastiaanc** [comment]
Does that mean a non-"god"admin can edit this?

**Comment by mkoch227** [comment]
The items in the "General" tab will stay in settings, so the permissions to modify those won't change. For "Statuses" and "UI Colors", there will be two new permissions for non-admins, named "Manage ticket statuses" and "Manage UI colors", respectively.

**Comment by bastiaanc** [comment]
Can "Manage ticket statuses" and "Manage UI colors" be switched off for non "god admins" ??

**Comment by mkoch227** [comment]
You will be able to restrict those features, yes.  Also in 2.3.0, permission groups will be added, allowing you to create different groups with different permission sets, instead of only having "Administrator" and "Staff".  Hopefully this will make more sense once it is actually implemented :smiley:

**Comment by bastiaanc** [comment]
Thanks Mike. I am just so thankful that you do all this :-)
