### ISSUE TITLE
"Please select"

### ISSUE THREAD

**Issue by bastiaanc** [mkoch227/Mods-for-HESK#197]
Can you please build in a "Please select" for the category?
Right now if a customer is too lazy, the category will be the first category :-(
![schermafbeelding 2015-04-12 om 17 29 19](https://cloud.githubusercontent.com/assets/9219295/7106197/d7fc7366-e139-11e4-9fd5-d0b6418b83c6.png)
I called the first category "please select", but even then they do not select it :-(
Thanks for all you do

**Comment by mkoch227** [comment]
This already exists in HESK 2.6.2. Check under Settings --> Help desk --> Features

![screen shot 2015-04-12 at 11 39 43 am](https://cloud.githubusercontent.com/assets/333430/7106254/d2044e2e-e108-11e4-9886-40411fa7a289.png)

**Comment by bastiaanc** [comment]
OMG! ;-) I am so sorry!
But thanks anyway. I just changed it :-)
