### ISSUE TITLE
Improve Search on Tickets Page

### ISSUE THREAD

**Issue by mkoch227** [mkoch227/Mods-for-HESK#203]
From UserVoice page:

> Make a search function or modify the which is already there. 
Move it from the bottom and up. Then it comes up over tickets.
It will make it much easier and search for tickets.
If you also want to be able to change it to like it as is on this page: http://www.hesk.com/demo/

No AJAX yet, until the AJAXify issue is finished.

**Comment by bastiaanc** [comment]
Is it possible to have it in here?
![schermafbeelding 2015-04-17 om 22 54 06](https://cloud.githubusercontent.com/assets/9219295/7210735/bc38afd6-e554-11e4-8d07-5ce11fdc9bb4.png)

**Comment by bastiaanc** [comment]
Can we have it like ... that you can either choose bottom or top. I personally think that a search bar above is not relevant enough compared to the ticket list. Maybe it could be a little button that would pop out when you click on it. At that moment (if you need it) it would be relevant. I personally would hate to see the tickets all pushed down for a feature that is not needed all the time.
However, if it really has to be on the top could it at least be an option to choose?

**Comment by mkoch227** [comment]
My plan is to streamline the search area, instead of it taking up a whole "block" of space. Perhaps it'll look similar to GitHub's search bar, but have a dropdown area to include an "advanced" search.

**Comment by bastiaanc** [comment]
You mean that it would fit in the main menu? Blue area?
That is already very wide in my case. If you use Dutch or German it is even wider :-(
Here is my utopic thought: Can it be a search (icon) symbol and when you click on it, it becomes a pop up (Ajax)?
Or something like this?: http://www.perfect-web.co/joomla/facebook-like-box-sidebar or more the Off-canvas idea?
http://getuikit.com/docs/offcanvas.html

**Comment by bastiaanc** [comment]
Sorry, or did you mean the "GitHub's search bar would come in here?
![schermafbeelding 2015-04-17 om 22 54 06](https://cloud.githubusercontent.com/assets/9219295/7210735/bc38afd6-e554-11e4-8d07-5ce11fdc9bb4.png)

**Comment by mkoch227** [comment]
It would either be in the tickets panel or just above it. Not sure yet, though.

**Comment by bastiaanc** [comment]
In the past I said "I personally think that a search bar above is not relevant enough compared to the ticket list"

Well ... I am one of the few. In our department the majority wants it on top because they need it so much :-)

So can't wait for your modification :-)

**Comment by mkoch227** [comment]
My plan is to add a search bar (the same size as the one on the home page for customers), along with an "advanced search" button/link that will show all of the additional filters. However, the "show tickets" panel will stay as-is; this will only affect "Find tickets".

**Comment by bastiaanc** [comment]
However, the "show tickets" panel will stay as-is; this will only affect "Find tickets".
Not sure what you mean here?

**Comment by bastiaanc** [comment]
Ok... we'll see. I am curious :-)

**Comment by mkoch227** [comment]
Due to the extreme fragility of this page (if I even try to move the "find tickets" section somewhere else, the whole page goes crazy), I'm going to defer working on this until the next release, so I can (hopefully) look into completely rewriting this page and making it a bit "better" in terms of design.
