### ISSUE TITLE
Show "top" and "latest" KB articles on dashboard

### ISSUE THREAD

**Issue by mkoch227** [mkoch227/Mods-for-HESK#205]
Add an option to display top and latest KB articles, similar to the UI of the regular version of HESK

**Comment by bastiaanc** [comment]
Is it possible to have this as an option? I would like to switch it off if not needed. If no knowledge base articles are available it would not be relevant on the home page.
I have nothing against this feature, but in most cases for me it is better like it is now :-)
I hope that it is possible and that I am not making things more difficult ;-)

**Comment by mkoch227** [comment]
There will definitely be an option. This will also never appear if the knowledgebase is disabled, as it wouldn't make sense to show "top articles" when there isn't even a knowledgebase :grinning:

**Comment by bastiaanc** [comment]
Well good to know that nothing is changing in my life ;-)
