### ISSUE TITLE
Request: Export Mod Hesk settings

### ISSUE THREAD

**Issue by PeopleInside** [mkoch227/Mods-for-HESK#207]
When i update Mod for Hesk i loose all time all settings of Mod like "show icon" now i will loose also status closable or not.. so please can you add an option for export Mod Hesk settings maybe in General.. and Import so i can export a file and import after update.

**Comment by mkoch227** [comment]
If you're on the latest version of Mods for HESK, you do **not** need to replace `modsForHesk_settings.inc.php` when updating.

**Comment by PeopleInside** [comment]
Understood, maybe can be userfull anyway :) thanks.

**Comment by mkoch227** [comment]
Also, "closable" statuses are database-driven, so they'll never be contained in the settings file (they are in the `hesk_statuses` table). So you don't need to worry about loosing that :smile:
