### ISSUE TITLE
cant execute SQL

### ISSUE THREAD

**Issue by syahidcaex** [mkoch227/Mods-for-HESK#211]
error. cant execute SQL. but my sql correct. i m sure about that.

**Comment by mkoch227** [comment]
Is this during installation? When searching? Turn debug mode on via settings, try again, and post a screenshot of the error.

**Comment by syahidcaex** [comment]
thank mike. so fast.  it ok now. i m fix at new sql. cannt duplicate db

**Comment by syahidcaex** [comment]
mike, you mod. awesome. btway. how if i want put button add like dat

n the. when me add country add database. when new ticket . if i choose
country "  cuba"  , assign the ticket automatick read cuba1 , cuba 2 , if i
choose country bacu , automatic Assign this ticket to: read bacu1 , bacu2

**Comment by syahidcaex** [comment]
​

**Comment by mkoch227** [comment]
Are you saying depending on the country selected (from a custom field I'm assuming), set the tracking ID to the country name, followed by the next available number?

**Comment by syahidcaex** [comment]
forget about dat.. i want just want assign group. example as picture

​when i choose option at besut , automatic it assign at Assign thist ticket
to,
like dat.

so assign this ticket to will assign
Bo mrsd Besut
Fo mrsd Besut
Hakim Mrsd Besut .. just "besut" will take. you understand what i say? sory
for my bad grammar. hahaha.
picture 1, i add custom field at setting.. hope you help me. you modd so
awesome! but i need to modified for this just for learn. if you cant help
for it. just tell me where page i need edit. thankfull mike![?][?]
​

**Comment by syahidcaex** [comment]
assign by name but just certain word like "besut "

**Comment by mkoch227** [comment]
Already responded to OP's email. Closing as this is beyond my support.
