### ISSUE TITLE
Empty Attachment Sent When Closing Ticket

### ISSUE THREAD

**Issue by bastiaanc** [mkoch227/Mods-for-HESK#213]
When a ticket is closed/resolved there is still an attachment in it with "0kb"
Please see attachment
![schermafbeelding 2015-04-16 om 11 20 26](https://cloud.githubusercontent.com/assets/9219295/7177910/ec06c2aa-e42a-11e4-93a3-eaacef722006.png)
So the attachments work when replying, but when a ticket is closed, the customer gets the closed ticket with an attachment that has 0kb's
Please let me know if you can regenerate this.

I am not sure if these are tickets that already had attachments in it before the system was updated from 2.1.0 to 2.2.0.
Thanks,

Bas

**Comment by mkoch227** [comment]
It appears that attachments are being sent, regardless if the message (%%MESSAGE%%) is included in the email. Since "vanilla" HESK only adds attachment links when %%MESSAGE%% is included, this will somehow need to be checked when sending emails before appending attachments.
