### ISSUE TITLE
Missing Outer Boundary Causes Outlook to Improperly Display Email

### ISSUE THREAD

**Issue by friend1422** [mkoch227/Mods-for-HESK#214]
Hesk 2.6.2 email piping was working ok. Added Mods-for-Hesk 2.2 and email piping is now no longer working are there any additional config changes required for 2.2 2

**Comment by mkoch227** [comment]
Can you do the following for me?

 1. Go to your helpdesk's `/inc/mail` folder. If there is a file named **error_log**, delete it.
 2. In HESK, go to Settings --> Help Desk and set "Debug Mode" to ON. Click save.
 3. Attempt to send an email through email piping.  Once you send the email, wait ~30 seconds.
 4. Go back to your helpdesk's `/inc/mail` folder and see if a file named **error_log** appeared. If so, copy and paste the contents of **error_log** here.

**Comment by friend1422** [comment]
Don't have access to server at the moment but will check later on may need reapply CHMOD to email file

**Comment by friend1422** [comment]
Have added 0755 permissions to hesk_pipe.php and it is now working - but the email sent to the customer is generated with the original email attached (as a text or HTML file) plus the email mime types in the email text.

![email](https://cloud.githubusercontent.com/assets/11976197/7188021/a88cc6ea-e46c-11e4-9bcc-96d544794861.jpg)

**Comment by mkoch227** [comment]
Can you send an email to me (mkoch227@gmail.com) with the following attached:
  - The email you sent to `hesk_pipe.php`
  - The email you received from HESK

If you can attach them as `.eml` file, that would be preferred.

**Comment by friend1422** [comment]
I have emailed you the files.
Email sent to hesk_pipe.php and returned from HESK. I have sent you two sets one sent from and to HESK 2.6.2 and one with HESK 2.6.2 + HESK MOD 2.2

**Comment by mkoch227** [comment]
Thanks for the emails. Outlook is very strict on its formatting rules, and, in this case, the email is missing a closing boundary that "wraps up" the email. Most email clients (GMail, AirMail, to name a few) will fix this automatically; however Outlook just goes "nope" and dumps everything out :frowning: It's a relatively simple fix and hopefully I'll have v2.2.1 out sometime this weekend.

**Comment by mkoch227** [comment]
@friend1422, can you download this version of `email_functions.inc.php` at https://raw.githubusercontent.com/mkoch227/Mods-for-HESK/2f33ec794c6f241c227edf63f3c8ab9c874cd29f/inc/email_functions.inc.php, upload it to your HESK instance, and see if this fixes the random attachment issue?  _(You may have to right-click on the link and select "Save Link As..." to actually download the file)_

**Comment by friend1422** [comment]
Thanks Mike, is working fine.

I tested with plain text email, and HTML email, both with and without attachments and the customer emails are now handled properly ;)
