### ISSUE TITLE
top knowledgebase articles not displaying correctly

### ISSUE THREAD

**Issue by friend1422** [mkoch227/Mods-for-HESK#216]
not showing views at all and not displaying properly on mobile

**Comment by mkoch227** [comment]
Can you provide me a screenshot / URL?

**Comment by PeopleInside** [comment]
Maybe can be userfull a screen shot here.

**Comment by friend1422** [comment]
banktree.co.uk/support

as shown on front page and when you click on view knowledgebase

**Comment by mkoch227** [comment]
Here's what I see on the homepage:
![screen shot 2015-04-16 at 8 32 16 am](https://cloud.githubusercontent.com/assets/333430/7180817/2ee34bc4-e413-11e4-8ed2-dc18e67f0621.png)

And what I see on the view knowledgebase page:
![screen shot 2015-04-16 at 8 33 16 am](https://cloud.githubusercontent.com/assets/333430/7180832/42355834-e413-11e4-867d-a44d483b8e2f.png)

Does this look the same to you? If not, what browser and version are you using?

**Comment by friend1422** [comment]
This is what it looks like in HESK note the Views are populated. I used the same code function to replicate this in the hesk-mod

![hesk](https://cloud.githubusercontent.com/assets/11976197/7180906/de0d238e-e43d-11e4-904f-f244b149c829.png)

**Comment by PeopleInside** [comment]
Yes, from Android 5.0 using Firefox or Chrome on Samsung Galaxy S 5 i see this:
![screenshot_2015-04-16-14-38-02](https://cloud.githubusercontent.com/assets/5006150/7180940/90ff753e-e446-11e4-92a6-ac961ec97d24.png)

why text can't be expanded and goes immediately head?

**Comment by friend1422** [comment]
@PeopleInside yes get same results as you in chrome and google browser on android phone

**Comment by friend1422** [comment]
To Add the Views:
Amend file /inc/knowledgebase_functions.php
line 118 replace the query with the following  (you need to include `t1`.`views` in the select)

    /* Get list of articles from the database */
    $res = hesk_dbQuery("SELECT `t1`.`id`,`t1`.`subject`,`t1`.`dt`, `t1`.`views` FROM `".hesk_dbEscape($hesk_settings['db_pfix'])."kb_articles` AS `t1`
			LEFT JOIN `".hesk_dbEscape($hesk_settings['db_pfix'])."kb_categories` AS `t2` ON `t1`.`catid` = `t2`.`id`
			WHERE `t1`.`type`='0' AND `t2`.`type`='0'
			ORDER BY `t1`.`sticky` DESC, `t1`.`views` DESC, `t1`.`art_order` ASC LIMIT ".intval($how_many));

To fix the Kb article display:
line 150 & 219  remove the width="200"
