### ISSUE TITLE
Pop Up Image .JPG (not .jpg)

### ISSUE THREAD

**Issue by bastiaanc** [mkoch227/Mods-for-HESK#217]
Somebody had send a .JPG instead of a .jpg and it did not pop-up. However when I was downloading it it was working. I renamed it from .JPG into .jpg and the same image worked in the pop up

**Comment by mkoch227** [comment]
It appears I'm making a case-sensitive comparison for the file extension instead of case insensitive. It'll be fixed in 2.2.1
