### ISSUE TITLE
------ Reply above this line ------

### ISSUE THREAD

**Issue by bastiaanc** [mkoch227/Mods-for-HESK#220]
Is it possible to have a
"------ Reply above this line ------"
In the ticket_closed.txt ?

The reason is that I have the following text in it:
"Just simply reply to this message to RE-OPEN your ticket."

Right now if the customer replies on the "closed message" there will not be an email or the ticket will not have a reply.

Hope that this a simple "fix"
Thanks so much

Reopen tickets in settings is "on"

**Comment by PeopleInside** [comment]
Interesting. I had no think to what happen if user reply to the closed email notification. Meybe this should be reported to hesk too.

Maybe your request is can reopen ticket if the user reply to the closed email notification.
Here two things, make the reply possible or make closed alert send from different no reply address. 

I think this should be implemented, maybe add the reply from the customer to the ticket if the customer reply to the email and ticket is not locked.

**Comment by PeopleInside** [comment]
Is not valid, as i see this work already. If you reply to the closed ticket alert the reply of the customer is added to the ticket. I had tested now and already works for me.. so seems this topic is invalid.

Maybe needs to be checked. From my test this already works and not need to be implemented.

**Comment by bastiaanc** [comment]
Are you using html templates?

**Comment by PeopleInside** [comment]
Yes in HTML works. Do you use plain text? Now i will test with TXT sorry. And update here by editing above.

**Comment by bastiaanc** [comment]
hmmm in plain text it works :-(
Seems to be something on my end

**Comment by PeopleInside** [comment]
Yes, tested and works in TXT also.
Maybe you have to check if your POP3 Fetching or Email piping are setup correctly, if the permission is correct and if you have a cron job, if they works.

Maybe your issue is from all email and reply sent not only in the closed ticket.
Good luck.
