### ISSUE TITLE
Request: Insert image logo

### ISSUE THREAD

**Issue by PeopleInside** [mkoch227/Mods-for-HESK#222]
Is possible to insert an image logo by adding the right code on the header.txt file but today i discover image put in this way is not responsive so bad look on mobile for all ticket system. This create issues.

So I think will be nice implement a logo upload from the settings and put the right code for make responsive.

**Comment by mkoch227** [comment]
That's possible. For now, try changing adding the `img-responsive` CSS class to your image (it's a bootstrap-specific class that adds responsive-like support to iamges):

```html
<img src="..." class="img-responsive" ...>
```

**Comment by PeopleInside** [comment]
Works great, thanks!

**Comment by syahidcaex** [comment]
how do you do it that? 
i put code at header.txt
<img src="img/logo.jpeg" class="img-responsive" ...>

**Comment by syahidcaex** [comment]
it s my code 


<pre>
img src="..&#47;img&#47;header1.PNG"   style="width:1604px;height:228px"  class="img-responsive" ...>
</pre>



when i go to localhost/hesk/admin

image can load sucessfully but when i go localhost/hesk

image can load unsucessfully. image broken. i dont know how to change directry

**Comment by mkoch227** [comment]
get rid of the `...` before `>`. It's not actual markup.

**Comment by mkoch227** [comment]
If a setting is added, how will the user be able to decide where the image goes? Top-left, top-center, top-right, stretch across, etc? Using header.txt allows the user to use any HTML markup they wish. Feel free to add this to the UserVoice page if you'd like. But for now, I don't see any necessary changes.
