### ISSUE TITLE
Request : Assign by real name

### ISSUE THREAD

**Issue by syahidcaex** [mkoch227/Mods-for-HESK#223]
Is possible to assign user for real name. if i have add user1,user2.user3, admin1,admin2,admin3. when new ticket , i choose select box at custom field just admin, at assign to tickt just out admin only. it awesome function. easy to send if many user add. This create issues.

So I think will be nice implement to create on function assign user like that.

**Comment by mkoch227** [comment]
All feature requests go to the UserVoice page, per the [contributing guidelines](https://github.com/mkoch227/Mods-for-HESK/blob/master/CONTRIBUTING.md). They do not go here.
