### ISSUE TITLE
Add option to disable update checking

### ISSUE THREAD

**Issue by mkoch227** [mkoch227/Mods-for-HESK#229]

**Comment by PeopleInside** [comment]
Why this? :O

**Comment by mkoch227** [comment]
Some users don't have cURL installed along with a setup that restricts `file_get_contents()` from accessing an external site, causing Mods for HESK to think there is always an update.

**Comment by PeopleInside** [comment]
Interesting. Maybe in this case if i understand well is good to think to add a server check in update and install who infor the user, if the option is supported user can enable if not not . Thanks for clarify

**Comment by mkoch227** [comment]
Just realized that HESK's auto-update setting already coorelates with Mods for HESK's update checking strategy, so this already exists.
