### ISSUE TITLE
Upload and Attachments improvment

### ISSUE THREAD

**Issue by PeopleInside** [mkoch227/Mods-for-HESK#235]
From uservoice
1.
Advanced upload, upload attachment/s with drag and drop
https://mods-for-hesk.uservoice.com/forums/254758-general/suggestions/7563459-advanced-upload-upload-attachment-s-with-drag-and

2.
upload bar progress admin and client side
https://mods-for-hesk.uservoice.com/forums/254758-general/suggestions/7787049-upload-bar-progress-admin-and-client-side

3.
Track download file and mark as downloaded
https://mods-for-hesk.uservoice.com/forums/254758-general/suggestions/7889310-track-download-file-and-mark-as-downloaded

**Comment by mkoch227** [comment]
If/once the UserVoice suggestions are marked as "Planned", issues will be created for them then. I separated feature requests to a separate place for a reason, which was to keep GitHub issues clean.
