### ISSUE TITLE
User Cannot Delete Category

### ISSUE THREAD

**Issue by mkoch227** [mkoch227/Mods-for-HESK#240]
.....after all this time, no one has had an issue where they cannot delete a category. However, it is currently impossible to do so!

**Comment by bastiaanc** [comment]
Hi Mike, I am able to do so! Not a problem at all :-) That is strange?
Do I have a different server maybe (Linux / Direct Admin)

**Comment by mkoch227** [comment]
Are you able to delete the KB category if there are 0 articles in it?

**Comment by bastiaanc** [comment]
Yes I am

Van:  Mike Koch <notifications@github.com>
Beantwoorden - Aan:  mkoch227/Mods-for-HESK
<reply+008cacdf27664b62e2de0ae3f6a12f5f5d0308372e72df0792cf000000011169bec79
2a169ce047e50fa@reply.github.com>
Datum:  dinsdag 12 mei 2015 15:14
Aan:  mkoch227/Mods-for-HESK <Mods-for-HESK@noreply.github.com>
CC:  Bas Cuppen
Onderwerp:  Re: [Mods-for-HESK] User Cannot Delete Category (#240)


Are you able to delete the KB category if there are 0 articles in it?


Reply to this email directly or view it on GitHub
<https://github.com/mkoch227/Mods-for-HESK/issues/240#issuecomment-101270678
> .

**Comment by bastiaanc** [comment]
Ups .... No I am not able to .... sorry
