### ISSUE TITLE
Submit Reply And Resolve

### ISSUE THREAD

**Issue by bastiaanc** [mkoch227/Mods-for-HESK#250]
Hi, When I "Submit reply and change status to Resolved" the reply will be sent but the closed ticket template is not. I was just thinking that this was a bug?

Thanks
![schermafbeelding 2015-06-07 om 15 38 49](https://cloud.githubusercontent.com/assets/9219295/8024205/b2849500-0d2b-11e5-9d01-f781ba5a5e4f.png)

**Comment by mkoch227** [comment]
I just ran a test against HESK 2.6.2 (without Mods for HESK), and only the reply is sent (this also keeps the customer's inbox slightly cleaner and may also be less confusing). Since the behavior of this is the same with "regular" HESK, I don't plan on changing this anytime soon.
