### ISSUE TITLE
Link of FAQ is wrong also the text is not translated and i can't translate in the language file.

### ISSUE THREAD

**Issue by PeopleInside** [mkoch227/Mods-for-HESK#260]
![2](https://cloud.githubusercontent.com/assets/5006150/8351350/e6226694-1b2c-11e5-8f0d-c3efc5915a50.png)
![3](https://cloud.githubusercontent.com/assets/5006150/8351351/e625055c-1b2c-11e5-8de3-bfe4386f7075.png)

**Comment by PeopleInside** [comment]
I really disagree with the move of the settings. I can't find animore nothing and i can't see different color. What sense have to move the mod of Hesk settings.

Very bad step. Very unhappy and now i can't find where activate icons, HTML emails, etc.

**Comment by mkoch227** [comment]
I purposely didn't add the text into the language file as that section is going to be completely removed in 2.4.0. I found that it wouldn't be useful to have it translated when I'm going to be removing it in a few months.

Link has been fixed.
