### ISSUE TITLE
Captcha not aligned in the center

### ISSUE THREAD

**Issue by PeopleInside** [mkoch227/Mods-for-HESK#261]
Captca is not aligned in the center. The input box seems ask to the user to digit the position. 

1. Captcha should be in center

2. Geolocalization (Posizione) should be more far to the captcha input box

**Comment by PeopleInside** [comment]
![5](https://cloud.githubusercontent.com/assets/5006150/8351998/f9f11e22-1b31-11e5-972b-9c31e944bdb6.png)

**Comment by PeopleInside** [comment]
How can i solve this?

**Comment by PeopleInside** [comment]
![immagine senza nome](https://cloud.githubusercontent.com/assets/5006150/8353564/8d08ffe2-1b3f-11e5-8d70-a5148421b770.png)

**Comment by mkoch227** [comment]
This is what I see right now:

![2015-06-25 07_09_29-help desk - submit a ticket](https://cloud.githubusercontent.com/assets/333430/8353588/9ccba01a-1b0d-11e5-8062-19fa73ba686c.png)

If you set your language to English, does the same issue occur?

**Comment by mkoch227** [comment]
Also, I do not have the styling that you pointed out. Is there any styling in your header/footer files that is propagating down to the CAPTCHA? Check out the page's source code at line 32 (where the dev tools say the styling is defined at)

**Comment by PeopleInside** [comment]
Yes same in English.  
I tried to remove the 0 in the browser and this solve the issue but I'm unable to understand what edit in Mod of Hesk

**Comment by mkoch227** [comment]
Look at my comment just before your response. I'm guessing you have custom styling in your header/footer that is causing it.

**Comment by PeopleInside** [comment]
What page? Index.php? Or header.txt and footer.txt?

Yes I have header and footer setup

**Comment by PeopleInside** [comment]
Ok i will check this files and let you know

**Comment by mkoch227** [comment]
> What page? Index.php? Or header.txt and footer.txt?

header.txt and footer.txt

**Comment by PeopleInside** [comment]
Cheched, I can't find nothing of strange.
Would like i send some where in private the footer and header files?

I think is not this the issue.. but maybe can be.. where i can send to you? Thanks

**Comment by PeopleInside** [comment]
Header have this code:

<style>  img {display: block; margin: 0 auto;}</style>
<img oncontextmenu= ";return false" src="https://peopleinside.it/webticket/img/webticket.png" class="img-responsive" width="740" height="145" alt="Logo Siti Web Marco Borla" border="0" />


Footer:

<center><h3><a href="https://www.peopleinside.it/termini-condizioni/" target="_blank">Termini & Condizioni</a> </h1></center>
<script type="text/javascript">
var LHCChatOptions = {};
LHCChatOptions.opt = {widget_height:450,widget_width:300,popup_height:715,popup_width:500};
(function() {
var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
var refferer = (document.referrer) ? encodeURIComponent(document.referrer.substr(document.referrer.indexOf('://')+1)) : '';
var location  = (document.location) ? encodeURIComponent(window.location.href.substring(window.location.protocol.length)) : '';
po.src = '//www.peopleinside.it/livechat/index.php/ita/chat/getstatus/(click)/internal/(position)/bottom_right/(ma)/br/(hide_offline)/true/(check_operator_messages)/true/(top)/350/(units)/pixels/(leaveamessage)/true/(department)/1/2/4/5/6/(noresponse)/true?r='+refferer+'&l='+location;
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
})();
</script>

**Comment by mkoch227** [comment]
`img {display: block; margin: 0 auto;}` <-- right there is the CSS that's causing the issue.

**Comment by PeopleInside** [comment]
I don't know why there is this code here. removed.. thanks.
