### ISSUE TITLE
Request to improve uploads

### ISSUE THREAD

**Issue by PeopleInside** [mkoch227/Mods-for-HESK#265]
- Once selected a file you can't remove it.
Please consider to implement advanced upload with progress bar drag and drop and possibility to remove a selected file for upload. If i select a file and after think this should not be uploaded as attacments i should have the remove button..

Also implement an upload bar progress.

https://mods-for-hesk.uservoice.com/forums/254758-general/suggestions/7563459-advanced-upload-upload-attachment-s-with-drag-and

https://mods-for-hesk.uservoice.com/forums/254758-general/suggestions/7787049-upload-bar-progress-admin-and-client-side

**Comment by bastiaanc** [comment]
You would have to buy him a beer first ;-) or maybe even a bottle of wine ;-)
http://mods-for-hesk.mkochcs.com/donate.php

**Comment by PeopleInside** [comment]
:-) Great message! Thanks @bastiaanc, you are right. Very sweet way to support jobs.
Thanks ! :) And hope to see in the future this implemented.

**Comment by mkoch227** [comment]
#275 Addresses these requests.  Also, as I stated before, please _**do not**_ copy over UserVoice requests here. They are split up for a reason. I will create GitHub issues on my own as I mark requests as "planned".
