### ISSUE TITLE
Updated to 2.3.2 but i see Hesk update avaiable 2.3.2

### ISSUE THREAD

**Issue by PeopleInside** [mkoch227/Mods-for-HESK#273]
I had updated Mod of Hesk at 2.3.2 but I see
![1](https://cloud.githubusercontent.com/assets/5006150/8397900/ca5b37ae-1ddb-11e5-84fd-4119c357dd92.png)

How can I fix?

Thanks

**Comment by mkoch227** [comment]
Try deleting _mfh-latest.txt in your attachments folder. I updated the site after the release, so it may just be a false-positive.

**Comment by PeopleInside** [comment]
Thank this fix the issue in my first website.
Now in the other website i have updated to 2.3.2 but i see i have 2.3.1 what to do here?

**Comment by mkoch227** [comment]
You can either (1) run the installer (if you didn't already) or (2) execute the following SQL query (which is what the installer does): 

```sql
UPDATE hesk_settings SET `Value` = '2.3.2' WHERE `Key` = 'modsForHeskVersion'`
```

**Comment by PeopleInside** [comment]
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`' at line 1

**Comment by mkoch227** [comment]
Sorry, take out the very last ` after 'modsForHeskVersion'.

**Comment by PeopleInside** [comment]
Fixed thanks!
