### ISSUE TITLE
Special tag guide is not present when you edit predefined reply

### ISSUE THREAD

**Issue by PeopleInside** [mkoch227/Mods-for-HESK#281]
Special tag line with Hesk variable for name, mail, ecc is only available if you make new predefined reply, not if you edit it by selecting an existent reply.

Can be useful add also in edit mode.

Step to reproduce:
1. Canned responses
2. Select a canned response 
3. the tag sentence for help to insert special tag is now hidden [Insert special tag (will be replaced with customer info):]

**Comment by mkoch227** [comment]
Should be an easy fix. In [`manage_canned.php`](https://github.com/mkoch227/Mods-for-HESK/blob/master/admin/manage_canned.php#L273-L300), move `</span>` on line 300 to be right after `</textarea>` on line 279.
