### ISSUE TITLE
Google V2 Captcha not working

### ISSUE THREAD

**Issue by bastiaanc** [mkoch227/Mods-for-HESK#282]

**Comment by mkoch227** [comment]
My recaptchas are working just fine for me. Please include a screenshot of your reCAPTCHA config page (from Google) and your helpdesk settings (feel free to hide your secret key / private key, but please include your public/site key (you can freely show the public key without any security risks)).  An example is below.

![screen shot 2015-07-12 at 10 58 19 am](https://cloud.githubusercontent.com/assets/333430/8638330/fc61f030-2885-11e5-8fb7-5a5a0f666d24.png)
![screen shot 2015-07-12 at 11 03 05 am](https://cloud.githubusercontent.com/assets/333430/8638332/02cf53ea-2886-11e5-84f1-24bef0cde629.png)

**Comment by bastiaanc** [comment]
Van:  Mike Koch <notifications@github.com>
Beantwoorden - Aan:  mkoch227/Mods-for-HESK
<reply+008cacdf008ee808dfe696540be8f8ad4fe31c790f28286792cf0000000111ba44949
2a169ce05a2d069@reply.github.com>
Datum:  zondag 12 juli 2015 17:07
Aan:  mkoch227/Mods-for-HESK <Mods-for-HESK@noreply.github.com>
CC:  Bas Cuppen <bas@cuppen.de>
Onderwerp:  Re: [Mods-for-HESK] Google V2 Captcha not working (#282)


My recaptchas are working just fine for me. Please include a screenshot of
your reCAPTCHA config page (from Google) and your helpdesk settings (feel
free to hide your secret key / private key, but please include your
public/site key (you can freely show the public key without any security
risks)).  An example is below.

 <https://cloud.githubusercontent.com/assets/333430/8638330/fc61f030-2885-11
e5-8fb7-5a5a0f666d24.png>
 <https://cloud.githubusercontent.com/assets/333430/8638332/02cf53ea-2886-11
e5-84f1-24bef0cde629.png>


Reply to this email directly or view it on GitHub
<https://github.com/mkoch227/Mods-for-HESK/issues/282#issuecomment-120727600
> .

**Comment by bastiaanc** [comment]
Please try to enable it and send a ticket in the front end. Does it work
when you send it?

Thanks

Van:  Mike Koch <notifications@github.com>
Beantwoorden - Aan:  mkoch227/Mods-for-HESK
<reply+008cacdf008ee808dfe696540be8f8ad4fe31c790f28286792cf0000000111ba44949
2a169ce05a2d069@reply.github.com>
Datum:  zondag 12 juli 2015 17:07
Aan:  mkoch227/Mods-for-HESK <Mods-for-HESK@noreply.github.com>
CC:  Bas Cuppen <bas@cuppen.de>
Onderwerp:  Re: [Mods-for-HESK] Google V2 Captcha not working (#282)


My recaptchas are working just fine for me. Please include a screenshot of
your reCAPTCHA config page (from Google) and your helpdesk settings (feel
free to hide your secret key / private key, but please include your
public/site key (you can freely show the public key without any security
risks)).  An example is below.

 <https://cloud.githubusercontent.com/assets/333430/8638330/fc61f030-2885-11
e5-8fb7-5a5a0f666d24.png>
 <https://cloud.githubusercontent.com/assets/333430/8638332/02cf53ea-2886-11
e5-84f1-24bef0cde629.png>


Reply to this email directly or view it on GitHub
<https://github.com/mkoch227/Mods-for-HESK/issues/282#issuecomment-120727600
> .

**Comment by bastiaanc** [comment]
Please try a test ticket here: https://www.cuppen.de/support/index.php?a=add
Thanks,

Bas

Van:  Mike Koch <notifications@github.com>
Beantwoorden - Aan:  mkoch227/Mods-for-HESK
<reply+008cacdf008ee808dfe696540be8f8ad4fe31c790f28286792cf0000000111ba44949
2a169ce05a2d069@reply.github.com>
Datum:  zondag 12 juli 2015 17:07
Aan:  mkoch227/Mods-for-HESK <Mods-for-HESK@noreply.github.com>
CC:  Bas Cuppen <bas@cuppen.de>
Onderwerp:  Re: [Mods-for-HESK] Google V2 Captcha not working (#282)


My recaptchas are working just fine for me. Please include a screenshot of
your reCAPTCHA config page (from Google) and your helpdesk settings (feel
free to hide your secret key / private key, but please include your
public/site key (you can freely show the public key without any security
risks)).  An example is below.

 <https://cloud.githubusercontent.com/assets/333430/8638330/fc61f030-2885-11
e5-8fb7-5a5a0f666d24.png>
 <https://cloud.githubusercontent.com/assets/333430/8638332/02cf53ea-2886-11
e5-84f1-24bef0cde629.png>


Reply to this email directly or view it on GitHub
<https://github.com/mkoch227/Mods-for-HESK/issues/282#issuecomment-120727600
> .

**Comment by mkoch227** [comment]
![screen shot 2015-07-12 at 11 16 01 am](https://cloud.githubusercontent.com/assets/333430/8638385/69a0e718-2887-11e5-9332-06bea77354f1.png)

**Comment by bastiaanc** [comment]
Not at all, all original

**Comment by mkoch227** [comment]
Ok. Can you provide screenshots of your config on the reCAPTCHA side, as well as your helpdesk config (similar to the example I provided)?

**Comment by bastiaanc** [comment]
On it's way per email

**Comment by mkoch227** [comment]
Are you trying to use that same reCAPTCHA for the helpdesk at `cuppen.de`?

**Comment by bastiaanc** [comment]
No not at all, cuppen.de is just an example.

**Comment by bastiaanc** [comment]
Do you need access to teh ticket system?

**Comment by mkoch227** [comment]
Ok. Can I try sending a test ticket to that helpdesk then?

**Comment by bastiaanc** [comment]
www.86fss.net/masupport/

**Comment by mkoch227** [comment]
Ok the issue occurs there as well. In either helpdesk, open `submit_ticket.php`, and find on line 151:

```php
if ($resp != null && $resp->success)
{
    $_SESSION['img_verified']=true;
}
else
{
    $hesk_error_buffer['mysecnum']=$hesklang['recaptcha_error'];
}
```

Just **BEFORE** that, add:
```php
die(var_dump($resp));
```

Then submit a ticket. The response will be blank, except for dumping the contents of the response. copy and paste the response here.

**Comment by bastiaanc** [comment]
object(ReCaptchaResponse)#3 (2) { ["success"]=> bool(false) ["errorCodes"]=> NULL }

**Comment by mkoch227** [comment]
Would you mind emailing me FTP credentials to your server so I can look at a few other things? (it would be faster than going back and forth).

**Comment by bastiaanc** [comment]
Just a mom

**Comment by bastiaanc** [comment]
just emailed

**Comment by mkoch227** [comment]
Ok I found your problem. It looks like `file_get_contents` is not working on your server (when your server sends the request to reCAPTCHA, nothing happens, only `boolean(false)` is returned, while I get back a JSON response). To fix this, you will need to open `php.ini` and set `allow_url_fopen = on` (currently it is off: see screenshot). If you don't know how to change this, I recommend talking with your server admin / hosting provider.

![screen shot 2015-07-12 at 11 53 22 am](https://cloud.githubusercontent.com/assets/333430/8638533/cac58a9e-288c-11e5-8cb0-8331098a2454.png)

**Comment by bastiaanc** [comment]
I know that allow_url_fopen is off on the whole server.
Joomla uses Curl
If you look at https://www.86fss.com/contact-us-eclub 
recaptca is working.
Is it because Joomla supports Curl?

**Comment by mkoch227** [comment]
It's possible that Joomla is using cURL instead of `file_get_contents` (which I actually recommend). It looks like the latest version of the reCAPTCHA PHP library (1.1.1) supports cURL, so it may be worth for me to look into upgrading the library for a future release. You can try upgrading the library on your own; however I cannot provide support for it as the problem is not Mods for HESK; it is technically the reCAPTCHA library being outdated.

**Comment by bastiaanc** [comment]
Unfortunately I would not know how to upgrade a library :-( If I would I would do it immediately :-)
I can only hope that you find some time in the future. Let me know if you need me to buy some software that would help you make it easy for you to implement

**Comment by mkoch227** [comment]
there's no need to purchase any software. I have everything I would need to do if I get to it. however, the easiest thing for you to do to get it working would be to enable `file_get_contents` for remote URLs.

**Comment by bastiaanc** [comment]
Hi Mike,
My server already replied following: From Php Version 5.1 "file_get_contents" function is completely removed for security reasons.
The only preferred command would be cURL.
I guess it is not possible for me?

**Comment by mkoch227** [comment]
As of now, no it is not possible. I can try adding cURL support to the current library, but there are no guarantees.

**Comment by mkoch227** [comment]
I created Issues #284 in reference to this issue. I'm going to close this for now since this is not an actual "issue" with Mods for HESK, but instead a current library limitation.
