### ISSUE TITLE
Permission Issues

### ISSUE THREAD

**Issue by bastiaanc** [mkoch227/Mods-for-HESK#292]
I made a Super Administrator with all permissions except for a few like “manage help desk”
I do not want to let them do Can manage Permision templates

Now when a super administrator (below administrator with full permissions) makes a new category he can not see the category anymore

For me the situation like it was that they were just not able to see the settings was ok. Now it is more complicated :-(

**Comment by bastiaanc** [comment]
I made a Super Administrator with all permissions except for a few like “manage help desk”
I do not want to let them do Can manage Permision templates

Now when a super administrator (below administrator with full permissions) makes a new category he can not see the category anymore


For me the situation like it was that they were just not able to see the settings was ok. Now it is more complicated :-(

**Comment by mkoch227** [comment]
Right now, if don't select the user to be an admin, the user will not be auto-added to additional categories that are created.  

I will add an option in 2.5.0 to set a user's category security to be "all categories", which will include any additional categories that may be created in the future.

**Comment by mkoch227** [comment]
(Absorbing this issue into #346)
