### ISSUE TITLE
Store User Agent Information

### ISSUE THREAD

**Issue by mkoch227** [mkoch227/Mods-for-HESK#326]
Not sure what the best way to do this is right now...

**Comment by mkoch227** [comment]
@FormidableMulk: I believe you stated in your UserVoice request that you had a way to retrieve the user agent and screen resolution of the customer. Do you, by chance, have any code snippets for obtaining this information? (It would make things much easier for me :grinning: )

**Comment by FormidableMulk** [comment]
@mkoch227: I can't recommend my solution; it worked for me, but I wasn't re-packaging my build for mass-use.

I permanently re-purposed custom fields to pull this off, then tweaked the default case of the _CUSTOM AFTER_ section of the ticket submission form.  (In the HESK v2.6.4, it looks like this is line 686-699 of index.php in the root directory.)

(I don't have access to what I previously did right now, so I'm going to attempt to recreate it below.  I haven't tested this against this version of HESK; I'm just winging it here.)


Drop a switch in at line 694 to handle re-purposed fields.

**Replace this**
```php
echo '
<tr>
<td style="text-align:right" width="150">'.$v['name'].': '.$v['req'].'</td>
<td width="80%"><input type="text" name="'.$k.'" size="40" maxlength="'.$v['maxlen'].'" value="'.$v['value'].'" '.$cls.' /></td>
</tr>
';
```

**With this**
```php
switch($k)
	{
		case 'custom1':
		$readonly = ' readonly="readonly"';
		$v['value'] = $_SERVER["HTTP_USER_AGENT"];
		break;

		case 'custom2':
		$readonly = ' readonly="readonly"';
		$v['value'] = null;

		default:
		$readonly = "";
	}

echo '
<tr>
<td style="text-align:right" width="150">'.$v['name'].': '.$v['req'].'</td>
<td width="80%"><input type="text" name="'.$k.'" id="'.$k.'" size="40" maxlength="'.$v['maxlen'].'" value="'.$v['value'].'" '.$cls.$readonly.' /></td>
</tr>
';
```
_**Note:** I added an **id** attribute to the input for faster DOM manipulation and a conditional **readonly** attribute to lock overridden custom fields._

Then, after the _for_ loop iterating through the CUSTOM AFTER section, you can use Javascript to override the _custom2_ value.

```HTML
<script>
document.getElementById("custom3").value = screen.width + " x " + screen.height;
</script>
```

This qualifies as quick and dirty; it's not versatile enough for every environment but it does capture useful data!

**Comment by mkoch227** [comment]
@FormidableMulk thanks for your response, it helped quite a bit :smile: .  2.5.0 will have three new columns (`user_agent`, `screen_resolution_width`, and `screen_resolution_height`) which will store this new information.  This way, no custom fields will be taken for this information :grinning:
