### ISSUE TITLE
If you merge two or more tickets Audit log are not merged

### ISSUE THREAD

**Issue by PeopleInside** [mkoch227/Mods-for-HESK#340]
Hi,
if you merge some ticket the only Audit Log will be the one of the tickets Audit Log, other ticket will loose log.

For example:
Ticket 1
removed attachment A and B
Ticket 2 removed attachment C

Ticket 1 and Two merged result= in the Audit log you will see only removed attachments C

**Comment by mkoch227** [comment]
This behavior is consistent with a "traditional" HESK installation; the merging process has not changed in Mods for HESK.  Post a topic on the PHP Junkyard Scripts forums to see what Klemen has to say. 

Audit merging improvements will be added in #212
