### ISSUE TITLE
Parts of code in page output

### ISSUE THREAD

**Issue by xZero707** [mkoch227/Mods-for-HESK#347]
Hi, I have latest version of Hesk, and since I didn't had any problems. I found Mods-for-HESK as awesome and decided to try them, which failed. I have followed the instructions and installed Mods-For-HESK on clean installation of Hesk 2.6.5

PHP 5.6.12-1~dotdeb+7.1 (MySQLi)
MySQL: 10.0.21-MariaDB-1~wheezy

Admin panel:
![fireshot capture 7 - help desk_ - https___support elite7hackers net_d](https://cloud.githubusercontent.com/assets/3281104/9709020/83d8bf24-5524-11e5-916a-9738559efebf.png)

Main page (index):
![fireshot capture 8 - help desk - https___support elite7hackers net_](https://cloud.githubusercontent.com/assets/3281104/9709032/ae715a02-5524-11e5-9736-aebb9fb910d5.png)

Submit ticket (notice MySQL error):
![fireshot capture 9 - help desk - submit a ticket - https___support elite7hackers net_index php_a add](https://cloud.githubusercontent.com/assets/3281104/9709060/101aaeac-5525-11e5-82e2-b578dd30b53b.png)

I never had problems running anything on my VPS, and still I have many things running just flawlessly. Mods-for-HESK is first with trouble, unfortunately.

**Comment by mkoch227** [comment]
It looks like your installation is echoing out the settings file when loading the custom CSS instead of properly parsing it.  Can you send me your helpdesk URL so I can take a look at how the stylesheet is being returned? If you don't want to share your URL here, you can send it to me via the contact form at http://mikekoch.me.

**Comment by xZero707** [comment]
It's ok to share URL: https://support.elite7hackers.net

Thank you for your time.

**Comment by mkoch227** [comment]
It looks like the PHP code that is in `hesk_newStyle` (which is CSS that either overrides Bootstraps or is custom CSS specifically for Mods for HESK) isn't being properly rendered first, which results in the garbage at the top of the screen.  Try this and see what happens:

  1. Open `css/hesk_newStyle.php` and find: `header("Content-type: text/css; charset: UTF-8");` and change it to `header("Content-type: text/css;");
  2. Save, upload, and test. (Also clear Cloudflare cache if necessary, as I noticed that your server is "cloudflare-nginx")

I'm also going to test Mods for HESK on PHP 5.6, as I'm currently using PHP 5.5 in all of my current installations to see if it's a PHP issue.

**Comment by xZero707** [comment]
It wasn't a issue,  however I  found it. 

In file modsForHesk_settings.inc.php there were not "<?php" tag at beginning. I don't know why, since I have checked install script and found (in file install/install_functions.inc.php:155) that it does write <?php.

**Comment by mkoch227** [comment]
Intetersting. I'm certain that the `<?php` tag is present in source control, so I'm not sure how it got removed. Glad you got it working though! :grinning:

**Comment by xZero707** [comment]
I don't know, maybe something to do with PHP 5.6
