### ISSUE TITLE
SMTP/POP3/MySQL testing doesn't work

### ISSUE THREAD

**Issue by xZero707** [mkoch227/Mods-for-HESK#355]
Testing connection to such services has worked(and works) with original HESK.
With Mods-For-HESK test resulting with infinite "Testing connection, this can take a while..." 
Obviously, since it's infinite there are never any results displayed.

**Comment by mkoch227** [comment]
I'm not having any issues with my current installation.  Once I had an "empty response" error during SMTP testing; however simply clicking "Test Connection" fixed it.  Additionally, none of the test code has changed, so nothing should be different between HESK and Mods for HESK.  If I get to it, I may convert the Javascript to use jQuery which may make things a bit more stable.

**Comment by xZero707** [comment]
It's odd. I'll try in Opera Browser to see if it works. I tested with Chrome.

**Comment by xZero707** [comment]
Same problem in Opera. Maybe something is faulty with my installation, I'll make a fresh install and try again.
