### ISSUE TITLE
Run Report Time Zone Bug

### ISSUE THREAD

**Issue by shobzz87** [mkoch227/Mods-for-HESK#357]
There is a Bug in "Run Report".

I am using hesk in NZ , My server time zone is US .
after increasing 17 Hours in hesk settings. New ticket goes to latest date eg 12 Sep right time.
But if you will "Run Reports" it will show into 11 Sep according to server US time Zone.

In other words, Ticket entered on 12 Sep will show in 11 Sep in Run Reports.

Friday, September 11, 2015 1 1 0 16:00:09

How to fix that??

**Comment by mkoch227** [comment]
This issue appears to occur in HESK (without Mods for HESK) as well as in Mods for HESK.  Try doing the following:

 1. Make a backup copy of `admin/reports.php`, so if something goes wrong, you can revert back to this copy.
 2. Open `admin/reports.php` in a plain-text editor (such as Notepad++)
 3. Find, around line 881: `<td><?php echo hesk_dateToString($k); ?></td>`
 4. Replace that line with: `<td><?php echo hesk_dateToString($k, 1, 0, 0, true); ?></td>`
 5. Save, upload, and test.

**Comment by shobzz87** [comment]
I have modified the line 953 on server . But no change.
after entering a job today on 13 sep, it still going to 12 sep report.

**Comment by mkoch227** [comment]
Klemen has confirmed the issue on the forums and has stated that there should be a fix in the next HESK release.

Closing this as this is not a Mods for HESK-specific issue.
