### ISSUE TITLE
Help Desk URL in setting is not changeable

### ISSUE THREAD

**Issue by shobzz87** [mkoch227/Mods-for-HESK#359]
Its default, what ever you will put inside URL it will not work.

In settings> helpdesk > helpdesk URL

It will remain default, what ever you will put it will not change.

More over if you will put other url  than on top left "header" it will not work. But on new ticket it will send an email to customer with modified url.

**Comment by mkoch227** [comment]
I can currently change my helpdesk URL setting with no problems.  I have seen some issues where Zend OPcache wasn't being cleared, so my version of PHP has opcache turned off.

About the header text: currently the URL for the helpdesk title on the navbar is set to the root of the helpdesk folder, regardless of what you set in the helpdesk URL setting.  I'll change that to use the helpdesk url setting in 2.5.0. See #361

**Comment by shobzz87** [comment]
new ticket email sent to client should remain default. and that url link in setting should be editable , so that we can use our website link, so that clients move back to website after clicking that.

**Comment by mkoch227** [comment]
The url link **is editable**. If something isn't saving correctly, it is most likely a server setting on your end.
