### ISSUE TITLE
hesk 2.6.5 How to add more status?

### ISSUE THREAD

**Issue by shobzz87** [mkoch227/Mods-for-HESK#360]
Hi mKoch,

I have a question, I have modified all codes as same as "on_hold".
payment_pending assigned no 6
waiting_parts assigned no 7
every thing goes fine but status doesn't change on selecting payment_pending it goes to on_hold
but on selecting waiting_parts it goes to new 

whats wrong I am not sure, I have followed on_hold and changed everywhere.

can you please give me a clue. although you have wrote a good code but I didn't like its view. I want older style but all changes what you have made. :)

If you will give me an idea than i will be really thankful to you.

**Comment by mkoch227** [comment]
Are you using "vanilla" HESK and not Mods for HESK? If so, this is the wrong place for support, as I do not provide support for vanilla HESK here.  The only thing I can say is to make sure your database column for `status` supports the new values.
