### ISSUE TITLE
Custom Field Alignment Issues

### ISSUE THREAD

**Issue by mkoch227** [mkoch227/Mods-for-HESK#396]
Some form groups aren't being closed properly, causing a weird cascading issue with some form groups. Not sure if it's causing issues with the validator or not though.

**Comment by bastiaanc** [comment]
![schermafbeelding 2015-10-29 om 15 06 44](https://cloud.githubusercontent.com/assets/9219295/10827448/611c411c-7e6f-11e5-85d7-68d763351d17.png)
