### ISSUE TITLE
Print Ticket 

### ISSUE THREAD

**Issue by vemoya** [mkoch227/Mods-for-HESK#399]
does not generate a print preview like with the regular HESK without the MODS.

**Comment by mkoch227** [comment]
What exactly is not working with print preview? The print function is currently working fine for me. Screenshots would also be helpful

**Comment by vemoya** [comment]
never mind some how the print.php file was not copied over. my mistake

Thanks for the quick reply

Should I remove the bug post or you will remove it? Please let me know.

Thanks

On Thu, Oct 29, 2015 at 12:40 PM, Mike Koch <notifications@github.com>
wrote:

> What exactly is not working with print preview? The print function is
> currently working fine for me. Screenshots would also be helpful
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mkoch227/Mods-for-HESK/issues/399#issuecomment-152260709>
> .
>



-- 

Victor E. Moya

Technology Department

Valley View ISD

9701 South Jackson Rd.

Pharr, Texas, 78577

Ph: (956) 340-1120 ext. 1123

Fax: (956) 843-3021

Web: www.vviewisd.net

E-Mail: vemoya@vviewisd.net

-- 
DISCLAIMER:
This message and attached files contains confidential information and is 
intended only for the individual named recipient. If you are not the named 
recipient addressee you must not disseminate, distribute or copy this 
e-mail. Please notify the sender immediately by e-mail and/or phone if you 
have received this e-mail by mistake and destroy this e-mail from your 
entire system. E-mail transmission cannot be guaranteed to be secure or 
error-free as information could be intercepted, corrupted, lost, destroyed, 
arrive late or incomplete, or contain viruses. Valley View ISD therefore 
will not accept liability for any errors or omissions in the contents of 
this message, which arise as a result of e-mail transmission. The views, 
opinions, conclusions and other information expressed in this electronic 
mail are not given or endorsed by Valley View ISD unless otherwise 
indicated by an authorized representative independent of this message.

**Comment by mkoch227** [comment]
I just closed the issue. you can't delete github issues
