### ISSUE TITLE
Delete Banned Email Address

### ISSUE THREAD

**Issue by bastiaanc** [mkoch227/Mods-for-HESK#416]
Delete Banned Email Address won't work!

**Comment by mkoch227** [comment]
Well that's not good :stuck_out_tongue: . If you have a old ticket for that email address, you can go to that ticket and click the red "no" icon to unban the email address.  If there are no tickets for that email, you can run the following query:

```sql
DELETE FROM `hesk_banned_emails`
WHERE `email` = 'the@email.address'
```

Where **hesk_** is your database prefix.

**Comment by bastiaanc** [comment]
Thanks very much Mike! :-)
I was able to find it in the Database.

**Comment by mkoch227** [comment]
Fixed for the next release. Make the changes shown in 45caec4 if you want to apply it to your current installation.
