### ISSUE TITLE
Issue/Bug of Mod of Hesk 2.5.2?: Unable to recover password so I cant login. Recover password make a ban.

### ISSUE THREAD

**Issue by PeopleInside** [mkoch227/Mods-for-HESK#423]
I has been banned for try too many time to log in, now I am unbanned from the system but when i receive the email for recover password and click it is printed a blank page an so I'Am unable to log in and reset password.

I am completely out of the Help Desk.
How can I do'
IS a bug with the new version?

I can't find error log on the server relative to this.

**Comment by PeopleInside** [comment]
After clicking on the reset link i see a blank page and if I try to request new reset email I see I AM banned... so maybe there is a bug or something similar. I have not done any access today only reset password and i have this only admin account... I am unable to log in.

**Comment by PeopleInside** [comment]
OK I have used the hesk tool for unban than I remember the old password so able to log in.

I have do the log out and tried to send an email for reset password.
Clicked on the link and blank page is again showed.
When I come back to the hesk and opened the password recovery I see I Am Banned.

I think there is a BUG in the new Hesk who make impossible reset password also the system do a ban after clicking the link for reset password.

Is an mod for hesk issue or just only my issue?
How to solve?

**Comment by PeopleInside** [comment]
Hi,
I can't see any update for now here.

Please let me know if you need more information or if you are able to reproduce that in the new version 2.5.2 of Mod of Hesk.
Hope this can be fixed soon in the next Hesk release.

**Comment by mkoch227** [comment]
@PeopleInside sorry for the delay.... I have been very busy lately :laughing: . The fix for this issue is at 4a87f9e if you want to make the change yourself. Otherwise, the next Mods for HESK release will contain this fix.

**Comment by PeopleInside** [comment]
Thanks for fixing ^_^
