### ISSUE TITLE
Maintenance Mode

### ISSUE THREAD

**Issue by bastiaanc** [mkoch227/Mods-for-HESK#446]
When I switch on maintenance mode the attachments in the tickets are resulting in dead links or sql errors for the admins.

**Comment by mkoch227** [comment]
This issue appears to be a bug in Vanilla HESK as well. I've opened a forum topic at http://developers.phpjunkyard.com/viewtopic.php?f=13&t=5502

**Comment by mkoch227** [comment]
Klemen confirmed the issue on the forums. I'm going to close this as it will be fixed in the next Vanilla HESK release.

**Comment by bastiaanc** [comment]
Thanks
