### ISSUE TITLE
Use anti-SPAM image & Validate

### ISSUE THREAD

**Issue by bastiaanc** [mkoch227/Mods-for-HESK#450]
If you use "ReCaptcha V2 API (recommended)"
the validate function > "Submit ticket" won't work.

It works well if you do the setting: Use anti-SPAM image "OFF"

**Comment by mkoch227** [comment]
I'm not exactly sure what your issue is. I am able to submit a ticket just fine using ReCaptcha V2.

**Comment by bastiaanc** [comment]
- When the form is not completely filled in in the normal situation the submit button is not active yet.
- When using ReCaptcha V2 the button is always active

**Comment by mkoch227** [comment]
Ah, okay. I see the issue now.  I'll try to look into it sometime tomorrow.

**Comment by mkoch227** [comment]
Fixed. Will be released in 2.5.3.
