### ISSUE TITLE
Signature Field length

### ISSUE THREAD

**Issue by t-m-b** [mkoch227/Mods-for-HESK#452]
Signature Field does not accommodate 1000 Chars.
The number of Chars accepted is significantly less.

**Comment by mkoch227** [comment]
I see the issue. In `admin/profile.php` at line 181, change "255" to "1000". https://github.com/mkoch227/Mods-for-HESK/blob/master/admin/profile.php#L181

**Comment by t-m-b** [comment]
Thank you very much for the quick response!

**Comment by mkoch227** [comment]
Fix is ready for the next release (which will be shortly after the next HESK release).

**Comment by t-m-b** [comment]
Cool! Thanks.
