### ISSUE TITLE
Multi-company support

### ISSUE THREAD

**Issue by extremeshok** [mkoch227/Mods-for-HESK#95]
Allow a single support desk to be used for multiple companies /sites.

Each with their own options and users + support staff.

Similar to the wordpress multisite.

**Comment by bastiaanc** [comment]
This would be absolutely awesome !
Keep up the good work Mike :-)

**Comment by mkoch227** [comment]
What benefit would multi-company support offer other than an easier upgrade process?  Would you want a user account to be able to access multiple companies at once? Or would they be on a direct 1-to-1 relationship?

**Comment by extremeshok** [comment]
Users to be able to access multiple companies at once and to be able to have companies with separate users.

**Comment by mkoch227** [comment]
Hmm, ok. Now another question: how would customers determine which company they are submitting a ticket to?

**Comment by extremeshok** [comment]
Either by email ( support@company.com ) or via the webinterface .. 

It's easy to assign a cname and detect the company according to the url

**Comment by bastiaanc** [comment]
For me it would be very important to have own forms to submit (for each company)

**Comment by zelenkovsky** [comment]
-1 overcomlicated. Please keep it simple.

**Comment by mkoch227** [comment]
If you can post this feature request at the Mods for HESK UserVoice page (as requested in the [contributing guidelines](https://github.com/mkoch227/Mods-for-HESK/blob/master/CONTRIBUTING.md)), it would be appreciated.  This way other users can vote on the issue rather than saying "+1", "-1" etc.

**Comment by bastiaanc** [comment]
Hi zelenkovsky ,
It may be to complicated for you. For me and others this would be really a good solution because we work with different disciplines but in 1 organization. 
So overcomplicated would count for you. Simple is when you would just keep this option disabled.

Thank you

**Comment by mkoch227** [comment]
The mission of HESK is to provide a simple helpdesk solution. Adding multicompany support directly into HESK violates that mission (in my opinion), and therefore will not be added.

(I do have an idea up my sleeve that might work in the future; however it will be a completely separate system from Mods for HESK and HESK entirely).

https://mods-for-hesk.uservoice.com/forums/254758-general/suggestions/7170341-multicompany-support
